### ISSUE TITLE
 OutOfMemoryError when trying to run com.google.ads.googleads.examples.basicoperations.GetAdGroups

### ISSUE THREAD

**Issue by csarmiento** [googleads/google-ads-java#124]
Got an OOM error when trying to run one of the examples.

I set  `-Xmx2512m` but even though i got the following error

```
Information:java: The system is out of resources.
Information:java: Consult the following stack trace for details.
Information:java: 	at com.sun.tools.javac.code.Scope.dble(Scope.java:173)
Information:java: 	at com.sun.tools.javac.code.Scope.enter(Scope.java:213)
Information:java: 	at com.sun.tools.javac.code.Scope.enter(Scope.java:202)
Information:java: 	at com.sun.tools.javac.code.Scope$StarImportScope.importAll(Scope.java:553)
Information:java: 	at com.sun.tools.javac.comp.MemberEnter.importAll(MemberEnter.java:165)
Information:java: 	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:525)
Information:java: 	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
Information:java: 	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
Information:java: 	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
Information:java: 	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
Information:java: 	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
Information:java: 	at com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:973)
Information:java: 	at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:299)
Information:java: 	at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:294)
Information:java: 	at com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:1908)
Information:java: 	at com.sun.tools.javac.comp.Resolve.findGlobalType(Resolve.java:2007)
Information:java: 	at com.sun.tools.javac.comp.Resolve.findType(Resolve.java:2081)
Information:java: 	at com.sun.tools.javac.comp.Resolve.findIdent(Resolve.java:2110)
Information:java: 	at com.sun.tools.javac.comp.Resolve.resolveIdent(Resolve.java:2384)
Information:java: 	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3170)
Information:java: 	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
Information:java: 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
Information:java: 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
Information:java: 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
Information:java: 	at com.sun.tools.javac.comp.Attr.attribBase(Attr.java:786)
Information:java: 	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1072)
Information:java: Errors occurred while compiling module 'google-ads'
Information:javac 1.8.0_202 was used to compile java sources
Information:2019-05-24 09:05 - Build completed with 1 error and 0 warnings in 11 m 38 s 632 ms
Error:java: OutOfMemoryError: insufficient memory
```

**Comment by nwbirnie** [comment]
Hey, couple of questions:

- How are you compiling the examples? Are you using Maven? Please provide the full command line used to compile.
- Which version of the JDK are you using? Is this an official Oracle JDK?
- Could you try setting a much higher -Xmx setting to javac, e.g. try setting -Xmx10G.

Best wishes,
Nick

**Comment by csarmiento** [comment]
Hi @nwbirnie, I was using IntelliJ, the problem went away when changed the compiler heap size, but found an easier way to run the examples by changing the version in the pom file from `2.0.1-SNAPSHOT` to `2.0.0`.

Thanks, you can close the issue as it seems a config thing, anyway I didn't invest more time in it after  `2.0.0` worked for me.

**Comment by nwbirnie** [comment]
Ah, yes I remember, the IntelliJ compiler needs more memory than the default. You can either tell IntelliJ to use Maven to compile or increase the heap size. 

Glad you got it fixed.
