### ISSUE TITLE
Bug from version 3.0.1 to 4.0.0

### ISSUE THREAD

**Issue by danieleago** [googleads/google-ads-java#167]
Mutate Campaign Budget 
-------
[Gax-1] WARN shaded.com.google.ads.googleads.lib.request.summary - FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v2.services.CampaignBudgetService/MutateCampaignBudgets, Endpoint: googleads.googleapis.com:443, CustomerID: XXXXX, RequestID: null, ResponseCode: INTERNAL, Fault: Panic! This is a bug!.
[Gax-1] INFO shaded.com.google.ads.googleads.lib.request.detail - FAILURE REQUEST DETAIL.
Request
MethodName: google.ads.googleads.v2.services.CampaignBudgetService/MutateCampaignBudgets
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=XXXXX, x-goog-api-client=gl-java/1.8.0_201 gapic/ gax/ grpc/}
Body: customer_id: "XXXXX"
operations {
  create {
    name {
      value: "Budget #Search XXXX"
    }
    amount_micros {
      value: 5000000
    }
    delivery_method: STANDARD
  }
}

Response
--------
Headers: null
Body: null
Failure message: null
Status: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:98)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:65)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:373)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:467)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:120)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:471)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:255)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:188)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1.start(CensusTracingModule.java:394)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1.start(CensusStatsModule.java:695)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at shaded.com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:94)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at shaded.com.google.ads.googleads.lib.logging.LoggingInterceptor$1.start(LoggingInterceptor.java:78)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:310)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:282)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:191)
	at shaded.com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at shaded.com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65)
	at shaded.com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at shaded.com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at shaded.com.google.ads.googleads.lib.ExceptionTransformingCallable.futureCall(ExceptionTransformingCallable.java:51)
	at shaded.com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at shaded.com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at shaded.com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at shaded.com.google.ads.googleads.v2.services.CampaignBudgetServiceClient.mutateCampaignBudgets(CampaignBudgetServiceClient.java:350)
	at shaded.com.google.ads.googleads.v2.services.CampaignBudgetServiceClient.mutateCampaignBudgets(CampaignBudgetServiceClient.java:324)
	at com.onetag.frontend.handlers.pagecontent.demand.integration.search.Util.addCampaignBudget(Util.java:111)
	at com.onetag.frontend.handlers.pagecontent.demand.integration.search.Util.createCampaign(Util.java:147)
	at com.onetag.frontend.handlers.pagecontent.demand.integration.search.GoogleManagement.manageRemoteGoogle(GoogleManagement.java:781)
	at com.onetag.frontend.handlers.pagecontent.demand.CampaignCreateHandler.lambda$handle$13(CampaignCreateHandler.java:1492)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
}.

**Comment by nwbirnie** [comment]
It looks like you're relocating the client library under shaded.*. Is it possible that the relocations do not include the resources from gRPC? 

You should have a file META-INF/services/io.grpc.LoadBalancerProvider on the path which looks like:

```
io.grpc.internal.PickFirstLoadBalancerProvider
io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider
```

**Comment by danieleago** [comment]
Right observation, thank you

**Comment by 1005419213zxf** [comment]
can you share your pom.xml ?  i dont't know how to add  io.grpc.internal.PickFirstLoadBalancerProvider
io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider  in pom.xml?
my client library under shade.*，I used the maven shade for packaging, and there was no problem running directly.  I only see io.grpc.LoadBalancerProvider in the maven packaged file

Thank  you

**Comment by nwbirnie** [comment]
I'm guessing you're missing the services resource transformer.

Take a look at the (pending) [PR here](https://github.com/googleads/google-ads-java/pull/99/files#diff-5ff1179aa988691c214b46799fccd7ddR242).
