### ISSUE TITLE
ClosedChannelException

### ISSUE THREAD

**Issue by tiger154** [googleads/google-ads-java#197]
When I request to get campaign data with multi-threads. 
some ad_accounts fail to get data with error '**ClosedChannelException**'

But when I try the ad_accounts with one by one it's working.
also Even though multi-threads request I control request to google server max 4 times within a second. 

So can you give me any clue what can be the reasons to be closed channels from Google servers.

Below is the message when I got an error message.

```
Request
-------
MethodName: google.ads.googleads.v2.services.GoogleAdsService/Search
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=xxxxxx, x-goog-api-client=gl-java/1.8.0_222 gapic/ gax/1.45.0 grpc/1.21.0}
Body: customer_id: "xxxxxx"
query: "SELECT campaign.id, campaign.name, campaign.start_date, campaign.end_date, campaign_budget.delivery_method, campaign_budget.amount_micros, campaign_budget.total_amount_micros, campaign_budget.period, campaign_budget.explicitly_shared,campaign.ad_serving_optimization_status, campaign.advertising_channel_sub_type, campaign.advertising_channel_type, campaign.app_campaign_setting.app_id, campaign.app_campaign_setting.app_store, campaign.app_campaign_setting.bidding_strategy_goal_type, campaign.base_campaign, campaign.bidding_strategy, campaign.bidding_strategy_type, campaign.campaign_budget, campaign.commission.commission_rate_micros, campaign.dynamic_search_ads_setting.domain_name, campaign.dynamic_search_ads_setting.feeds, campaign.dynamic_search_ads_setting.language_code, campaign.dynamic_search_ads_setting.use_supplied_urls_only, campaign.end_date, campaign.experiment_type, campaign.final_url_suffix, campaign.frequency_caps, campaign.geo_target_type_setting.negative_geo_target_type, campaign.geo_target_type_setting.positive_geo_target_type, campaign.hotel_setting.hotel_center_id, campaign.id, campaign.labels, campaign.manual_cpc.enhanced_cpc_enabled, campaign.manual_cpm, campaign.manual_cpv, campaign.maximize_conversion_value.target_roas, campaign.maximize_conversions, campaign.name, campaign.network_settings.target_content_network, campaign.network_settings.target_google_search, campaign.network_settings.target_partner_search_network, campaign.network_settings.target_search_network, campaign.payment_mode, campaign.percent_cpc.cpc_bid_ceiling_micros, campaign.percent_cpc.enhanced_cpc_enabled, campaign.real_time_bidding_setting.opt_in, campaign.resource_name, campaign.selective_optimization.conversion_actions, campaign.serving_status, campaign.shopping_setting.campaign_priority, campaign.shopping_setting.enable_local, campaign.shopping_setting.merchant_id, campaign.shopping_setting.sales_country, campaign.start_date, campaign.status, campaign.target_cpa.cpc_bid_ceiling_micros, campaign.target_cpa.cpc_bid_floor_micros, campaign.target_cpa.target_cpa_micros, campaign.target_cpm, campaign.target_impression_share.cpc_bid_ceiling_micros, campaign.target_impression_share.location, campaign.target_impression_share.location_fraction_micros, campaign.target_roas.cpc_bid_ceiling_micros, campaign.target_roas.cpc_bid_floor_micros, campaign.target_roas.target_roas, campaign.target_spend.cpc_bid_ceiling_micros, campaign.target_spend.target_spend_micros, campaign.targeting_setting.target_restrictions, campaign.tracking_setting.tracking_url, campaign.tracking_url_template, campaign.url_custom_parameters, campaign.vanity_pharma.vanity_pharma_display_url_mode, campaign.vanity_pharma.vanity_pharma_text, campaign.video_brand_safety_suitability FROM campaign"
page_size: 5000

Response
--------
Headers: null
Body: null
Failure message: null
Status: Status{code=UNKNOWN, description=channel closed, cause=java.nio.channels.ClosedChannelException
        at io.grpc.netty.shaded.io.grpc.netty.Utils.statusFromThrowable(Utils.java:202)
        at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.exceptionCaught(WriteBufferingAndExceptionHandler.java:84)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:282)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:261)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:253)
        at io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.userEventTriggered(ProtocolNegotiators.java:343)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:312)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:304)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:348)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1789)
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1071)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
        at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
}.
```

**Comment by jradcliff** [comment]
Hi,

When running with multiple threads, are you using a separate instance of `GoogleAdsService` (via [`createGoogleAdsServiceClient`](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/reporting/GetKeywordStats.java#L95)) for each thread?

Thanks,
Josh, Google Ads API Team

**Comment by tiger154** [comment]
Hi Josh,

Thanks for your answer.
Yes for sure we use a separate instance of GoogleAdsService for each thread. 

And it was working well for a long time. This error just happens couple of weeks ago.

Here just short example of how we run multi-thread, and how we separate the instance of GoogleAdsService


1. How to run thread below 
```
Runnable task = () -> {
	try
		{
			controller.start();
		}
		catch (Throwable e)
		{
			log.error("ERROR", e);
	        }
	};

       threadPool.submit(task); // Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors()  * 2) 
```

2. Inside Runnable task() main logic 
```
GoogleAdsClient googleAdsClient  =  GoogleAdsClient.newBuilder().fromProperties(props).build(); 

 try (GoogleAdsServiceClient googleAdsServiceClient = googleAdsClient.getLatestVersion().createGoogleAdsServiceClient()) {
     // 1. Get all campaign for ad_account X 
     // 2. Get all adgroup for ad_account X 
     // 3. Get all ad for ad_account X 
     // 4. Get all insight_lifetime for ad_account X 
     // 5. Get all insight_daily for ad_account X 
}
```

**Comment by jradcliff** [comment]
When you run multi-threaded do you see any other errors before the channel exception? For example, if running multi-threaded puts enormous memory pressure on the JVM, you may see sporadic errors logged before the thread finally fails.

Thanks

**Comment by tiger154** [comment]
Hi Josh,

## Today all system working fine some how  
No there are no any other errors before channel closed. 

And **Surprisingly Today all system works totally just fine somehow and we didn't change any code**... 

But we gonna keep monitoring the status for this week. 


I still gonna give you more information about this weird error just in case.


## Problem we face were two below

  1) `Channel closed`
  2) `Wait too long to get response from google.(ex: waiting over 2 days to get data.. but still waiting)`
      - It looks like no timeout set??? or we can't set timeout?

When `channel closed happen` at least we can retry for failed one.
But actual critical problem is second one which can wait looks like forever we call as zombie thread holding connection (we saw 2 days waiting no timeout)

 
And this is more information for errors occurrence about number 1 case. 

1. ` io.grpc.StatusRuntimeException: UNKNOWN: channel closed`
2. ` javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake`
3. `java.lang.OutOfMemoryError: Java heap space`
4. `cause=java.net.SocketException: Broken pipe (Write failed)`
5. `java.lang.OutOfMemoryError: GC overhead limit exceeded`

**Comment by nwbirnie** [comment]
Closing since no activity, please reopen if this continues to be a problem.
