### ISSUE TITLE
java.lang.IllegalStateException: Could not find policy 'pick_first'

### ISSUE THREAD

**Issue by halmadgi** [googleads/google-ads-java#203]
Hi,

I am trying to get performance reports for Keyword and Ad. But getting error message "**Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files**" while execution.

I am using google api client maven jar as in a shaded application.Let me know how to resolve this issue.

Detailed request and response as below:
2019-12-19 13:11:14,051 [Gax-1] WARN  c.g.a.googleads.lib.request.summary - FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v2.services.GoogleAdsService/Search, Endpoint: googleads.googleapis.com:443, CustomerID: 8XXXXXXXX2, RequestID: null, ResponseCode: INTERNAL, Fault: Panic! This is a bug!.
2019-12-19 13:11:14,052 [Gax-1] INFO  c.g.ads.googleads.lib.request.detail - FAILURE REQUEST DETAIL.
**Request**
-------
MethodName: google.ads.googleads.v2.services.GoogleAdsService/Search
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, login-customer-id=8XXXXXXXX2, x-goog-api-client=gl-java/1.8.0_111 gapic/ gax/ grpc/}
Body: customer_id: "8XXXXXXXX2"
query: "SELECT campaign.id,ad_group.id,ad_group_criterion.criterion_id,ad_group_criterion.keyword.match_type,ad_group_criterion.quality_info.quality_score,ad_group_criterion.position_estimates.first_page_cpc_micros,ad_group_criterion.effective_cpc_bid_micros,ad_group_criterion.effective_cpc_bid_source,metrics.impressions,metrics.cost_micros,metrics.clicks FROM keyword_view DURING LAST_30_DAYS"
page_size: 1000

**Response**
--------
Headers: null
Body: null
Failure message: null
**Status: Status{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.**
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:98)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:65)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:373)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:467)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:120)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:471)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:255)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:188)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1.start(CensusTracingModule.java:394)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1.start(CensusStatsModule.java:695)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:94)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor$1.start(LoggingInterceptor.java:78)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:310)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:282)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:191)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:86)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.ads.googleads.lib.ExceptionTransformingCallable.futureCall(ExceptionTransformingCallable.java:51)
	at com.google.api.gax.rpc.PagedCallable.futureCall(PagedCallable.java:62)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.ads.googleads.v2.services.GoogleAdsServiceClient.search(GoogleAdsServiceClient.java:247)
	at com.thesearchagency.services.client.google.impl.serviceclient.ReportServiceClient.downloadReport(ReportServiceClient.java:72)

**Comment by jradcliff** [comment]
Hi,

I found [this fix on a related issue](https://github.com/grpc/grpc-java/issues/5493#issuecomment-478500418). Could you let me know if that fix works for you as well?

Thanks,
Josh Radcliff, Google Ads API Team

**Comment by halmadgi** [comment]
Thank you Josh,

It helped me in resolving the issue. Just that the serviceResourceTransformer need to be added in both poms.

<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>

- Anil Kumar Halmadgi
