### ISSUE TITLE
Internal error on getCustomer method

### ISSUE THREAD

**Issue by Evgentoz** [googleads/google-ads-java#328]
This method worked, yesterday. I don't know what happened.
this code
```
public List<CustomerDto> getCustomers(long projectId) {
        var project = projectRepository.getOne(projectId);
        var accessToken = googleUserAuthService.getActualAccessToken(project.getId(), ApiType.GOOGLE_ADS);

        try (var customerServiceClient = adsClientComponent.buildAdsClient(accessToken).getLatestVersion()
                .createCustomerServiceClient()) {

            var response = customerServiceClient.listAccessibleCustomers(ListAccessibleCustomersRequest.newBuilder().build());

            return response.getResourceNamesList().stream()
                    .map(customerServiceClient::getCustomer)
                    .map(customer -> new CustomerDto(
                            customer.getId().getValue(),
                            customer.getDescriptiveName().getValue(),
                            customer.getManager().getValue()
                    ))
                    .collect(Collectors.toList());
        } catch (Exception ex) {
            throw new GoogleServiceApiException(ex.getMessage(), ex.getCause());
        }

public GoogleAdsClient buildAdsClient(String accessToken) {
        var googleAdsCredentials = appApiCredentialRepository.findByApiType(ApiType.GOOGLE_ADS)
                .orElseThrow(() -> new AppApiCredentialsNotFoundException(ApiType.GOOGLE_ADS));

        return GoogleAdsClient.newBuilder()
                .setCredentials(GoogleCredentials.newBuilder()
                        .setAccessToken(new AccessToken(accessToken, null))
                        .build())
                .setDeveloperToken(googleAdsCredentials.getDeveloperToken())
                .build();
    }
```
```
Failure request summary Method: google.ads.googleads.v4.services.CustomerService/GetCustomer, Endpoint: googleads.googleapis.com:443, CustomerID: customers/2099226796, RequestID: null, ResponseCode: INTERNAL, Fault: Internal error encountered.

Request
-------
MethodName: google.ads.googleads.v4.services.CustomerService/GetCustomer
Endpoint: googleads.googleapis.com:443
Headers: {developer-token=REDACTED, x-goog-api-client=gl-java/11.0.8 gapic/ gax/1.49.1 grpc/1.23.0}
Body: resource_name: "customers/2099226796"
```

```
Response
--------
Headers: Metadata(content-type=application/grpc,date=Wed, 26 Aug 2020 14:46:29 GMT,alt-svc=h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: null
Failure message: null
Status: Status{code=INTERNAL, description=Internal error encountered., cause=null}.
2020-08-26 17:46:29.077 ERROR 22907 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.itsm.stratflag.api.model.exception.integration.google.GoogleServiceApiException: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.] with root cause

```
```
io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:111)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jradcliff** [comment]
Hi,

I see that you're using a `Get` request to retrieve each of your customers. Per our [Best Practices](https://developers.google.com/google-ads/api/docs/best-practices/quotas#get_requests), `Get` methods are meant for limited use such as learning the API or debugging, so the API has a limit of 1,000 such requests per day, per developer token.

Are you submitting more than 1,000 `Get` requests per day, perhaps?

Thanks,
Josh

P.S. Going forward, please reach out on the [forum](https://groups.google.com/forum/#!forum/adwords-api) for issues like this one which aren't specific to the client library for Java.

**Comment by jradcliff** [comment]
Hi,

My apologies, but right after I sent my previous reply, I discovered there was an issue earlier today specifically related to the `GetCustomer` method. Could you retry your requests and let me know if you're still seeing errors?

My earlier recommendation about moving away from `Get` in favor of [`GoogleAdsService.Search()` or `GoogleAdsService.SearchStream()`](https://developers.google.com/google-ads/api/reference/rpc/v4/GoogleAdsService) still applies, so please look into making that change as well to avoid hitting API limits.

Thanks

**Comment by Evgentoz** [comment]
@jradcliff Thanks for reply and advice,
GetCustomer method works now. 
I tried making logic through GoogleAdsService.Search()  but there need to specify customerId in the request.

Thanks
