### ISSUE TITLE
FATAL ERROR: java.lang.IllegalArgumentException: Invalid relative name: META-INF\services\javax.annotation.processing.Processor

### ISSUE THREAD

**Issue by din-heg-sie** [googleads/google-ads-java#340]
I cloned https://github.com/googleads/google-ads-java.git to my windows 10 desktop.
When I do a mvn compile, I get this error message:

**Which version of the client library are you using?**
Google Ads API Client Library for Java - v9.0.0
(https://github.com/googleads/google-ads-java/releases/tag/9.0.0)

**Which version of Java are you using?**
JDK 1.8

**Which operating system (Linux, Windows, ...) and version?**
Windows 10

**Actions taken**
1) I went to the folder where the git was cloned to C:\Users\dhegde1\projects\google-ads-java
2) mvn clean compile

**Expected result**
Expect compilation to complete succesfully without errors

**Actual result**
ERROR] FATAL ERROR: java.lang.IllegalArgumentException: Invalid relative name: META-INF\services\javax.annotation.processing.Processor
        at com.sun.tools.javac.file.JavacFileManager.getFileForOutput(JavacFileManager.java:737)
        at com.sun.tools.javac.processing.JavacFiler.getResource(JavacFiler.java:467)
        at com.google.auto.service.processor.AutoServiceProcessor.generateConfigFiles(AutoServiceProcessor.java:171)
        at com.google.auto.service.processor.AutoServiceProcessor.processImpl(AutoServiceProcessor.java:116)
        at com.google.auto.service.processor.AutoServiceProcessor.process(AutoServiceProcessor.java:104)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:635)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1041)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1206)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

 
**Anything else we should know about your project / environment**
I have attached the mvn log 

[google-ads-java - compile error - invalid relative name.txt](https://github.com/googleads/google-ads-java/files/5247368/google-ads-java.-.compile.error.-.invalid.relative.name.txt)

**Comment by devchas** [comment]
From the logs you provided, it looks like this is an issue with the [AutoService](https://github.com/google/auto/tree/master/service), which is a dependency of this library. For an immediate fix, please try the solution outlined [here](https://github.com/sockeqwe/annotationprocessing101/issues/4) by changing the [relevant line in this library](https://github.com/googleads/google-ads-java/blob/8c7bd1487da41274f73c50b304bdc0a6c184f220/google-ads-annotation-processing/pom.xml#L59). 

Please let us know if that fixes your problem. In that case, we'll evaluate whether we should incorporate this change into this library.

**Comment by nwbirnie** [comment]
Closing due to no activity. Please feel free to reopen if necessary.
