### ISSUE TITLE
no response from server after migrating to 9.0

### ISSUE THREAD

**Issue by madc0w** [googleads/google-ads-java#351]
see here:
https://stackoverflow.com/questions/64269197/google-ads-api-no-response-from-server-after-migrating-to-9-0

We were recently forced to migrate our Java Google Ads backend from 4.1.0 (v2) to 9.0.0 (v5). While all requests are now functioning normally in our local development environment, the identical requests fail from our Heroku server, in both test & prod.

Specifically:

        final GenerateKeywordIdeasPagedResponse response = keywordPlanIdeaServiceClient.generateKeywordIdeas(request);

never responds. This is only true on the deployed app. Locally, everything is fine. Account ID, client ID, client secret, developer token, login customer ID, refresh token, and service account user are all identical in both dev and test environments.

No error is thrown. Requests simply fail to respond. The Heroku server simply gives a 503 after timing out after 30 seconds, with no further information provided.

We've been rolling back to previous SDK/API versions. Here are the results:

    SDK 9.0.0/API v5 FAIL
    SDK 9.0.0/API v4 FAIL
    SDK 8.0.0/API v4 FAIL
    SDK 7.0.0/API v4 FAIL
    SDK 6.0.0/API v4 WORKS!!! miraculously

**Comment by nwbirnie** [comment]
Can you grab the gRPC logs for a call that hangs? They are logged to slf4j, and instructions for configuring this are available [here](https://developers.google.com/google-ads/api/docs/client-libs/java/logging).

The logger we're looking for is `io.grpc=ALL`.

**BE VERY CAREFUL TO REDACT AUTHENTICATION CREDENTIALS BEFORE POSTING HERE**

The gRPC logs will contain unredacted authentication headers (starting Authentication: Bearer: ....) and developer token (developer-token: ....). Please strip these before posting.

**Comment by nwbirnie** [comment]
Also this sounds like it's probably a dependency related issue. I would suggest verifying that you have a consistent set of dependencies between your local and Heroku environments. Which build system are you using for each?

**Comment by madc0w** [comment]
Thanks for that.  And yep, logging was our first thought.  We even found the same article to which you linked us.  Sadly, however:
https://stackoverflow.com/questions/64277081/how-to-log-to-googleads-requests

We've followed the advice given here: https://developers.google.com/google-ads/api/docs/client-libs/java/logging

Neither of the proposed solutions have any visible effect on what is logged to the console, either in dev or in deployment.

**Comment by nwbirnie** [comment]
I'm guessing that log4j isn't picking up your configuration file. You can try running with `-Dlog4j.debug` which should print some helpful debugging info about where it's looking for configs.

Also, can you post your command line invocation and which slf4j dependencies you're using please?

**Comment by madc0w** [comment]
Thanks for that!

Here is my local command line, as created by Eclipse:

"C:\Program Files\Java\jdk-13.0.2\bin\javaw.exe" -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:61794 -Dmaven.home=EMBEDDED -Dclassworlds.conf=C:\Users\mad\eclipse-workspace-java\.metadata\.plugins\org.eclipse.m2e.launching\launches\m2conf8504121200360559788.tmp -Dm2e.workspace.state=C:\Users\mad\eclipse-workspace-java\.metadata\.plugins\org.eclipse.m2e.core\workspacestate.properties -Dmaven.multiModuleProjectDirectory=C:\Users\mad\git\balloonary-backend -Xmx1g -Djava.util.logging.config.file=./resources/jdk-logger.properties -Dlog4j.debug -javaagent:C:\Users\mad\eclipse\java-2020-06\eclipse\configuration\org.eclipse.osgi\222\0\.cp\lib\javaagent-shaded.jar -Dfile.encoding=Cp1252 -classpath C:\Users\mad\.p2\pool\plugins\org.eclipse.m2e.maven.runtime_1.16.0.20200610-1735\jars\plexus-classworlds-2.6.0.jar org.codehaus.plexus.classworlds.launcher.Launcher -B -X -e clean compile exec:java


as for Heroku, here is the Procfile:

web: java $JAVA_OPTS -Dserver.port=$PORT -Djava.util.logging.config.file=./jdk-logger.properties -cp target/classes:target/dependency/* io.balloonary.Main

Locally, I see this on startup (with or without the -Dlog4j.debug option you suggested, which seems to be ignored):

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/mad/.p2/pool/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.16.0.20200610-1735/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/C:/Users/mad/eclipse/java-2020-06/eclipse/configuration/org.eclipse.osgi/5/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/mad/.p2/pool/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.16.0.20200610-1735/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/C:/Users/mad/eclipse/java-2020-06/eclipse/configuration/org.eclipse.osgi/5/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]

Heroku, however, nothing has nothing whatsoever to say about any logs, neither on build nor on startup.

**Comment by nwbirnie** [comment]
So there's a couple of issues which will stop logs being generated here.

1. **It looks like there's multiple slf4j implementations on the classpath**. slf4j is only a facade and requires a binding to a logger implementation to actually produce logs. However, in your case you have multiple such bindings and as a result it's likely that you'll get no useful output.
1. It looks like you're specifying JUL configuration, so `-Dlog4.debug` won't do anything. I inferred that you were using log4j from your stackoverflow thread.

I'm assuming that your project already logs to java.util.logging. In this case you should add the following dependency to your project:

```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-jdk14</artifactId>
  <version>1.7.25</version>
</dependency>
```

Next you should run `mvn dependency:tree` and find any other slf4j implementations on the classpath and remove them in favour of `slf4j-jdk14`. Then you should be able to enable the `io.grpc=ALL` logging in your `./jdk-logger.properties`

**Comment by madc0w** [comment]
First, thanks for your patience, I know this must be about as much fun for you as it is for me! You've been great so far.

Now, here is what I see when I examine the dependency tree for slf4j in Eclipse:
![Screenshot 2020-10-09 162829](https://user-images.githubusercontent.com/477541/95595498-84fe9080-0a4c-11eb-9eb5-57f3c1456402.png)

So, as you can see, there appears to be only the slf4j-jdk14 implementation in the dependencies.

Nonetheless, I've tried various "exclusions", all to no avail.

This seems to be a fairly well-known issue, as you can see here:
https://stackoverflow.com/questions/14024756/slf4j-class-path-contains-multiple-slf4j-bindings
Sadly, none of these solutions have been useful to me (so far).

Here is what I have at the moment:

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jdk14</artifactId>
			<version>1.7.25</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.m2e.maven.runtime.slf4j.simple</groupId>
					<artifactId>slf4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.osgi</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

None of this, however, makes any difference to the behavior described previously.

**Comment by nwbirnie** [comment]
So I'm not familiar with the Eclipse dependency view so I can't really advise based on that. If you had the output of `mvn dependency:tree` that would be useful.

I can see though that your exclusion is in the wrong place. When you specify an exclusion it has to go on the parent dependency which includes the dependency you want to exclude. In your case, it seems extremely unlikely that `slf4j-jdk14` depends on anything from eclipse.

Can you also share your JUL config file please?

**Comment by madc0w** [comment]
Progress... maybe?
Since I have no idea where this "org.eclipse.m2e.maven.runtime.slf4j.simple" dependency is defined (it's certainly not in the pom, so just weird), I replaced the Eclipse's embedded maven with the external system maven, and... no more "multiple SLF4J bindings" errors!

However! Still, no logs.

Here is jdk-logger.properties.  It lives under src/main/resources, but I'm not at all convinced it's being used at all:

handlers=java.util.logging.ConsoleHandler
com.google.ads.googleads.lib.logging.request.level=FINE
com.google.ads.googleads.lib.logging.request.level=FINE
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
io.grpc=ALL

Since you asked, here is the result of mvn dependency:tree
[deps.txt](https://github.com/googleads/google-ads-java/files/5355964/deps.txt)
As you can see, there is only one reference to org.slf4j:slf4j-jdk14:jar:1.7.25 here

**Comment by nwbirnie** [comment]
Looks like this is the offending dependency: `com.google.guava:guava:jar:25.1-android:compile` This should be version `28.2-android`.

**Comment by madc0w** [comment]
OK, I used an absolute path to specify the location of jdk-logger.properties.  No change.

Funny, though... I see this on the console:

[DEBUG] ignoreDelta true
[INFO] Copying 3 resources
[DEBUG] file application.properties has a filtered file extension
[DEBUG] copy C:\Users\mad\git\balloonary-backend\src\main\resources\application.properties to C:\Users\mad\git\balloonary-backend\target\classes\application.properties
[DEBUG] file jdk-logger.properties has a filtered file extension
[DEBUG] copy C:\Users\mad\git\balloonary-backend\src\main\resources\jdk-logger.properties to C:\Users\mad\git\balloonary-backend\target\classes\jdk-logger.properties
[DEBUG] file log4j.properties has a filtered file extension
[DEBUG] copy C:\Users\mad\git\balloonary-backend\src\main\resources\log4j.properties to C:\Users\mad\git\balloonary-backend\target\classes\log4j.properties
[DEBUG] no use filter components

I see this whether I use a relative path, like before, or the absolute path you recommend.

So.... any idea what "ignoreDelta" means or whose idea that is? Not mine.  Google search was unproductive.

I've been searching for a way to specify these properties in an XML file instead, but no luck so far.

**Comment by jradcliff** [comment]
I think the `ignoreDelta` is coming from the maven resources plugin:

https://issues.apache.org/jira/browse/MSHARED-516

Before we get too involved in this logging question, did you try the suggestion from @nwbirnie in his [previous comment](https://github.com/googleads/google-ads-java/issues/351#issuecomment-706258727)? I don't want to distract from the main goal of getting your app to run again. :)

**Comment by madc0w** [comment]
Well, it was a nice idea.  This guava thing was being dragged along by something called guice, which it turns out was totally superfluous. So I removed that, and here is the new dependency tree:
[deps2.txt](https://github.com/googleads/google-ads-java/files/5356200/deps2.txt)

com.google.guava:guava:jar:28.2-android

Great.

But.... no change in behavior.  Still, no response from server.

**Comment by nwbirnie** [comment]
Looks like you're also missing `io.grpc:grpc-core:jar:1.30.0:compile`.

![Screenshot from 2020-10-09 17-26-46](https://user-images.githubusercontent.com/410275/95608233-bed39500-0a54-11eb-9548-309e8f434599.png)

**Comment by madc0w** [comment]
OK then, added:
		<dependency>
			<artifactId>grpc-core</artifactId>
			<groupId>io.grpc</groupId>
			<version>1.30.0</version>
		</dependency>

This has no effect, which is somewhat expected, since the project compiles fine without that.
Also, none of this explains why everything works (worked) locally, but not when deployed to the Heroku server.

**Comment by madc0w** [comment]
Back to the logging issue, bear in mind that, of course, Heroku never had any of these extraneous Eclipse dependencies, and the whole "multiple SLF4J bindings" misadventure was never really an issue in deployment.  So, back to square 1... why no logs??

**Comment by nwbirnie** [comment]
The configuration file for JUL is incorrect:

This line:
```
io.grpc=ALL
```

Should be:
```
io.grpc.level=ALL
```

Can you also add a `Logger.getLogger("io.grpc.test").warn("some message")` to check that the logging is configured correctly please?

**Comment by nwbirnie** [comment]
Also what artifact do you publish to Heroku? Is it a .war file? How is this generated?

**Comment by madc0w** [comment]
No .war file here.  Heroku simply builds (maven) from the specified git branch, and then launches, based on the command found in Procfile (see above).  The Java version used by Heroku is 1.8.

Could you please specify the classpath for "Logger"?  I see five possibilities (not including the interfaces), but none of them allow Logger.getLogger("io.grpc.test").warn("some message") to compile.
![Screenshot 2020-10-09 204126](https://user-images.githubusercontent.com/477541/95620029-d4a28380-0a6f-11eb-8be0-254501d0365c.png)

**Comment by nwbirnie** [comment]
This is the one: https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/Logger.html

Should be `warning("some message")` rather than `warn("some message")`

**Comment by madc0w** [comment]
Yep. So now I see:

WARNING: some message

Nothing more interesting than that. And only locally. Heroku server doesn't even show this message.

**Comment by jradcliff** [comment]
You mentioned [earlier](https://github.com/googleads/google-ads-java/issues/351#issuecomment-706265000) that you tried setting `java.util.logging.config.file` to an absolute path. When deploying to Heroku, are you confident that path exists _on the Heroku server_ where the app is deployed?

Another brute force approach you could take would be to configure the `LogManager` at runtime, when your application starts up (at some point before your first request).

## Option 1 - try to get LogManager to read your config file from your classpath

As mentioned earlier, `java.util.logging.config.file` won't work with resources on the classpath, but you can do this at runtime via something like:

```
LogManager.readConfiguration(Resources.getResource("jdk-logger.properties").openStream());
```

## Option 2 - skip the config file and configure LogManager manually

```
LogManager.getGlobal().setLevel(Level.ALL);
Handler handler = new java.util.logging.ConsoleHandler();
handler.setLevel(Level.ALL);
LogManager.getGlobal().setHandler(handler);
```

**Comment by madc0w** [comment]
Success!!!
but I think you meant:

   		LogManager.getLogManager().readConfiguration(Resources.getResource("jdk-logger.properties").openStream());

but yeah, that kicked it in the right place! Great idea.

Unfortunately, I'm not sure how fruitful this was. Here are the annotated logs:
[logs.docx](https://github.com/googleads/google-ads-java/files/5358626/logs.docx)

**Comment by nwbirnie** [comment]
I agree that the stacktrace about `InternalCensusStatsAccessor` doesn't appear to be related to the issue.

Please can you attempt to construct a minimal failing example? Starting with an empty project, add the client library as a dependency and call `generageKeywordIdeas()`. Next add a few of your projects dependencies and try again. Keep doing this until you find a dependency that when added breaks the configuration. The upload the project here and I'll try to debug.

**Comment by madc0w** [comment]
Here is my little test project:
[v5-test.zip](https://github.com/googleads/google-ads-java/files/5369898/v5-test.zip)
on Github:
https://github.com/madc0w/google-ads-v5-test

Of course, all this works fine locally.
Deploying to Heroku is proving problematic, but I'm not sure what would be gained anyway, as you would have no access to that server. Anyway, I'll keep trying to do that.

**Comment by nwbirnie** [comment]
I'm looking now. Your test app contains Google account credentials in the file `./v5-test/V5Test.launch`. I would strongly suggest revoking these credentials (1) revoke the refresh token on accounts.google.com, and (2) reset your developer token on ads.google.com.

**Comment by madc0w** [comment]
Ugh, you're right, of course. I figured these were all test-related values (not prod), so not too worried about them... but the developer token is of course the same in both environments.
We will reset it soon.

**Comment by nwbirnie** [comment]
So I think this appears to be caused by having dots in your environment variable names. I just changed the app to pass these with underscores and it appears to just work...

```
2020-10-13T11:32:21.816593+00:00 heroku[worker.1]: State changed from starting to up
2020-10-13T11:32:23.174634+00:00 app[worker.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8
2020-10-13T11:32:23.294870+00:00 app[worker.1]: building google ads client
2020-10-13T11:32:27.250837+00:00 app[worker.1]: starting...
2020-10-13T11:32:28.093917+00:00 app[worker.1]: starting request
2020-10-13T11:32:29.815212+00:00 app[worker.1]: Exception in thread "main" com.google.ads.googleads.v5.errors.GoogleAdsException: errors {
2020-10-13T11:32:29.815223+00:00 app[worker.1]: error_code {
2020-10-13T11:32:29.815224+00:00 app[worker.1]: authorization_error: CUSTOMER_NOT_ENABLED
2020-10-13T11:32:29.815225+00:00 app[worker.1]: }
2020-10-13T11:32:29.815225+00:00 app[worker.1]: message: "The customer can\'t be used because it isn\'t enabled."
2020-10-13T11:32:29.815225+00:00 app[worker.1]: }
2020-10-13T11:32:29.815228+00:00 app[worker.1]: 
2020-10-13T11:32:29.815356+00:00 app[worker.1]: at com.google.ads.googleads.v5.errors.GoogleAdsException$Factory.createException(GoogleAdsException.java:42)
2020-10-13T11:32:29.815402+00:00 app[worker.1]: at com.google.ads.googleads.v5.errors.GoogleAdsException$Factory.createException(GoogleAdsException.java:34)
2020-10-13T11:32:29.815436+00:00 app[worker.1]: at com.google.ads.googleads.lib.BaseGoogleAdsException$Factory.createGoogleAdsException(BaseGoogleAdsException.java:105)
2020-10-13T11:32:29.815472+00:00 app[worker.1]: at com.google.ads.googleads.lib.GoogleAdsExceptionTransformation.transform(GoogleAdsExceptionTransformation.java:35)
2020-10-13T11:32:29.815511+00:00 app[worker.1]: at com.google.ads.googleads.lib.ExceptionTransformingCallable$ExceptionTransformingFuture.onFailure(ExceptionTransformingCallable.java:83)
2020-10-13T11:32:29.815546+00:00 app[worker.1]: at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
2020-10-13T11:32:29.815617+00:00 app[worker.1]: at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039)
2020-10-13T11:32:29.815644+00:00 app[worker.1]: at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
2020-10-13T11:32:29.815692+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
2020-10-13T11:32:29.815772+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
2020-10-13T11:32:29.815808+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
2020-10-13T11:32:29.815843+00:00 app[worker.1]: at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:179)
2020-10-13T11:32:29.815878+00:00 app[worker.1]: at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
2020-10-13T11:32:29.815914+00:00 app[worker.1]: at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
2020-10-13T11:32:29.815957+00:00 app[worker.1]: at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
2020-10-13T11:32:29.815989+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
2020-10-13T11:32:29.816023+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
2020-10-13T11:32:29.816057+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
2020-10-13T11:32:29.816102+00:00 app[worker.1]: at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
2020-10-13T11:32:29.816141+00:00 app[worker.1]: at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
2020-10-13T11:32:29.816173+00:00 app[worker.1]: at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
2020-10-13T11:32:29.816209+00:00 app[worker.1]: at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
2020-10-13T11:32:29.816244+00:00 app[worker.1]: at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039)
2020-10-13T11:32:29.816319+00:00 app[worker.1]: at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
2020-10-13T11:32:29.816401+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
2020-10-13T11:32:29.816437+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
2020-10-13T11:32:29.816471+00:00 app[worker.1]: at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
2020-10-13T11:32:29.816504+00:00 app[worker.1]: at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:545)
2020-10-13T11:32:29.816552+00:00 app[worker.1]: at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
2020-10-13T11:32:29.816586+00:00 app[worker.1]: at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
2020-10-13T11:32:29.816713+00:00 app[worker.1]: at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
2020-10-13T11:32:29.816714+00:00 app[worker.1]: at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
2020-10-13T11:32:29.816714+00:00 app[worker.1]: at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:111)
2020-10-13T11:32:29.816748+00:00 app[worker.1]: at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
2020-10-13T11:32:29.816788+00:00 app[worker.1]: at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
2020-10-13T11:32:29.816844+00:00 app[worker.1]: at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
2020-10-13T11:32:29.816878+00:00 app[worker.1]: at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
2020-10-13T11:32:29.816918+00:00 app[worker.1]: at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
2020-10-13T11:32:29.816949+00:00 app[worker.1]: at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
2020-10-13T11:32:29.817003+00:00 app[worker.1]: at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2020-10-13T11:32:29.817031+00:00 app[worker.1]: at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2020-10-13T11:32:29.817066+00:00 app[worker.1]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-10-13T11:32:29.817155+00:00 app[worker.1]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-10-13T11:32:29.817192+00:00 app[worker.1]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-10-13T11:32:29.817228+00:00 app[worker.1]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-10-13T11:32:29.817263+00:00 app[worker.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-10-13T11:32:29.817361+00:00 app[worker.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-10-13T11:32:29.817382+00:00 app[worker.1]: at java.lang.Thread.run(Thread.java:748)
2020-10-13T11:32:29.817548+00:00 app[worker.1]: Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
2020-10-13T11:32:29.817591+00:00 app[worker.1]: at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
2020-10-13T11:32:29.817612+00:00 app[worker.1]: at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
2020-10-13T11:32:29.817644+00:00 app[worker.1]: at com.google.ads.googleads.v5.services.KeywordPlanIdeaServiceClient.generateKeywordIdeas(KeywordPlanIdeaServiceClient.java:188)
2020-10-13T11:32:29.817699+00:00 app[worker.1]: at v5test.V5Test.run(V5Test.java:34)
2020-10-13T11:32:29.817743+00:00 app[worker.1]: at v5test.V5Test.main(V5Test.java:78)
2020-10-13T11:32:29.818171+00:00 app[worker.1]: Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission
2020-10-13T11:32:29.818224+00:00 app[worker.1]: at io.grpc.Status.asRuntimeException(Status.java:533)
2020-10-13T11:32:29.818294+00:00 app[worker.1]: ... 20 more
2020-10-13T11:32:30.198524+00:00 heroku[worker.1]: Process exited with status 1
2020-10-13T11:32:30.239581+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by nwbirnie** [comment]
Here's my code for [reference](https://github.com/nwbirnie/google-ads-v5-test). I removed `loginCustomerId` and `serviceAccountUser` since they weren't relevant to my authentication (I don't think this should make any difference).

Also here's a screenshot of the Heroku config for reference (with sensitive info removed).
![Screenshot from 2020-10-13 12-44-08](https://user-images.githubusercontent.com/410275/95856470-fc386b00-0d51-11eb-8740-9109c2e19186.png)

**Comment by madc0w** [comment]
Strange. These env vars with dots work fine in prod.  Anyway, I did as you suggested, but still can't deploy to Heroku.

Anyway, I had to move all the files up one directory so that Heroku could find the pom.xml, and I also added the <build> section you have in your pom.  Now everything works! So, thanks for that.

Now I'll be adding dependencies one by one, as you suggested. So stay tuned!

**Comment by nwbirnie** [comment]
Oh yes - the dependency copy? That could be it as well... it was needed because Heroku couldn't locate GoogleAdsClient so was throwing `ClassNotFoundException` on startup. I noticed in your Procfile that dependencies were loaded from `target/dependencies`.

If so it's probably worth trying adding that directly to your project and see if it fixes things.

**Comment by madc0w** [comment]
Well, that's that.  It works!!!
I don't pretend to understand why, but these changes to pom.xml make everything better.

![image](https://user-images.githubusercontent.com/477541/95865800-5bed4100-0d67-11eb-9cb4-7c3439a6db53.png)

Thanks so much for your help! You've been awesome.
