### ISSUE TITLE
Sporadic messages "Channel ManagedChannelImpl was not shutdown properly!!! "

### ISSUE THREAD

**Issue by debedb** [googleads/google-ads-java#399]
Getting log messages with stack traces as follows

```
Feb 08, 2021 5:06:32 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=473, target=googleads.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:340)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:73)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:214)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:221)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:204)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.ads.googleads.v6.services.stub.GrpcGoogleAdsServiceStub.create(GrpcGoogleAdsServiceStub.java:97)
	at com.google.ads.googleads.v6.services.stub.GoogleAdsServiceStubSettings.createStub(GoogleAdsServiceStubSettings.java:186)
	at com.google.ads.googleads.v6.services.GoogleAdsServiceClient.<init>(GoogleAdsServiceClient.java:130)
	at com.google.ads.googleads.v6.services.GoogleAdsServiceClient.create(GoogleAdsServiceClient.java:111)
	at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V6Client.createGoogleAdsServiceClient(GeneratedCatalog.java:6370))
```

Seems like this is due to a [resource leak](https://github.com/grpc/grpc-java/issues/7022).

**Comment by nwbirnie** [comment]
This is most likely because you have not closed a connection. The stacktrace is showing you where the dangling connection was created.

When you call `googleAdsClient.getLatestVersion().createFooServiceClient()` the library will create a new TCP connection. This needs to be cleaned up. So you should either surround the `createFooServiceClient()` in try-with-resources, or manually call `FooServiceClient.close()`.

**Comment by noamyogev84** [comment]
Hey,
Sorry for bringing the thread back.
I get this exception when I call connect.
I have a stress test where i'm trying to connect multiple different gRPC clients to my server. each client (worker) flow is pretty simple:
 1. Connect
 2. request some date (unary)
 3. disconnect (with shutdown() & awaitTermination)

when I run +100 parallel Workes I sporadically get this exception when a client connects to the server
What am I doing wrong?

**Comment by jradcliff** [comment]
Hi @noamyogev84 ,

You mentioned "i'm trying to connect multiple different gRPC clients to **my** server". Are you doing this in the context of _this_ library (google-ads-java), or are you instead setting up a gRPC service of your own? If the latter, then please continue to follow up on https://github.com/grpc/grpc-java/issues/9662.

Thanks,
Josh, Google Ads API Team

**Comment by noamyogev84** [comment]
Hi @jradcliff,
I'm developing a service of my own. More details here #9662
Thanks for the hint.
