### ISSUE TITLE
NoSuchMethodError after upgrading to v 14.0.0

### ISSUE THREAD

**Issue by visl** [googleads/google-ads-java#460]
**Which version of the client library are you using?**
14.0.0
**Which version of Java are you using?**
11
**Which operating system (Linux, Windows, ...) and version?**
Mac Catalina
**Actions taken**
Please provide a code snippet or steps to consistently reproduce the experienced behavior.
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA IN YOUR SUBMITTED CODE]
I have upgraded all referenced to the API to use version 8 and when I run

googleAdsClient.getLatestVersion().createAdGroupCriterionServiceClient()

I get

java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.StubSettings$Builder com.google.ads.googleads.v8.services.stub.AdGroupCriterionServiceStubSettings$Builder.setMtlsEndpoint(java.lang.String)'
at com.google.ads.googleads.v8.services.stub.AdGroupCriterionServiceStubSettings$Builder.createDefault(AdGroupCriterionServiceStubSettings.java:258) ~[google-ads-14.0.0.jar:na]
at com.google.ads.googleads.v8.services.stub.AdGroupCriterionServiceStubSettings$Builder.access$000(AdGroupCriterionServiceStubSettings.java:183) ~[google-ads-14.0.0.jar:na]
at com.google.ads.googleads.v8.services.stub.AdGroupCriterionServiceStubSettings.newBuilder(AdGroupCriterionServiceStubSettings.java:162) ~[google-ads-14.0.0.jar:na]
at com.google.ads.googleads.v8.services.AdGroupCriterionServiceSettings$Builder.createDefault(AdGroupCriterionServiceSettings.java:165) ~[google-ads-14.0.0.jar:na]
at com.google.ads.googleads.v8.services.AdGroupCriterionServiceSettings$Builder.access$000(AdGroupCriterionServiceSettings.java:145) ~[google-ads-14.0.0.jar:na]
at com.google.ads.googleads.v8.services.AdGroupCriterionServiceSettings.newBuilder(AdGroupCriterionServiceSettings.java:127) ~[google-ads-14.0.0.jar:na]
at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V8Client.createAdGroupCriterionServiceClient(GeneratedCatalog.java:4100) ~[google-ads-14.0.0.jar:na]
at com.wayfair.adtech.adverts.services.google.upload.keywords.KeywordGoogleUploadService.createKeywords(KeywordGoogleUploadService.java:68) ~[classes/:na]
**Expected result**
The code should return AdGroupCriterionServiceClient googleClient
**Actual result**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by nwbirnie** [comment]
It's likely that you have a conflicting version of some of our dependencies.

Here is the list of the [expected dependencies](https://gist.github.com/nwbirnie/ed533130ed823d4a311a7d173ecaa62f) for v14.0.0. Can you check your dependencies against this?

The specific depedency that you have an issue with is gax, so adding a direct dependency on `com.google.api:gax:1.65.1` should do the trick.

**Comment by visl** [comment]
Thanks, upgrading gax and gax-grpc to 1.66.0 resolved the issue

**Comment by nwbirnie** [comment]
Glad to hear it, thanks for confirming.
