### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64

### ISSUE THREAD

**Issue by aditya-protonn** [googleads/google-ads-java#462]
```
> Task :CreateJobWithStaticOverlay.main()
13:33:57.089 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
13:33:57.096 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - Platform: MacOS
13:33:57.098 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
13:33:57.098 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - Java version: 11
13:33:57.101 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:33:57.101 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:33:57.101 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:33:57.103 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:238)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:232)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:74)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:82)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:38)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:24)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:325)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
	at com.google.cloud.video.transcoder.v1beta1.stub.GrpcTranscoderServiceStub.create(GrpcTranscoderServiceStub.java:158)
	at com.google.cloud.video.transcoder.v1beta1.stub.TranscoderServiceStubSettings.createStub(TranscoderServiceStubSettings.java:277)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.<init>(TranscoderServiceClient.java:142)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.create(TranscoderServiceClient.java:123)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.create(TranscoderServiceClient.java:114)
	at com.protonn.googletranscoder.CreateJobWithStaticOverlay.createJobWithStaticOverlay(CreateJobWithStaticOverlay.java:37)
	at com.protonn.googletranscoder.CreateJobWithStaticOverlay.main(CreateJobWithStaticOverlay.java:28)
13:33:57.104 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
13:33:57.105 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3e11f9e9
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:352)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:343)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:74)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:82)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:38)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:24)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:325)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
	at com.google.cloud.video.transcoder.v1beta1.stub.GrpcTranscoderServiceStub.create(GrpcTranscoderServiceStub.java:158)
	at com.google.cloud.video.transcoder.v1beta1.stub.TranscoderServiceStubSettings.createStub(TranscoderServiceStubSettings.java:277)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.<init>(TranscoderServiceClient.java:142)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.create(TranscoderServiceClient.java:123)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.create(TranscoderServiceClient.java:114)
	at com.protonn.googletranscoder.CreateJobWithStaticOverlay.createJobWithStaticOverlay(CreateJobWithStaticOverlay.java:37)
	at com.protonn.googletranscoder.CreateJobWithStaticOverlay.main(CreateJobWithStaticOverlay.java:28)
13:33:57.106 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
13:33:57.106 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:33:57.143 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - maxDirectMemory: 4294967296 bytes (maybe)
13:33:57.144 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/8l/_7qky9cj38z5s8fzxxxs2ctr0000gn/T (java.io.tmpdir)
13:33:57.144 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:33:57.147 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
13:33:57.147 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
13:33:57.148 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
13:33:57.148 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
13:33:57.272 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /var/folders/8l/_7qky9cj38z5s8fzxxxs2ctr0000gn/T (io.netty.tmpdir)
13:33:57.272 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
13:33:57.272 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
13:33:57.273 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'io_grpc_netty_shaded_netty_tcnative_osx_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path: [/Users/aditya/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
	at java.base/java.lang.System.loadLibrary(System.java:1871)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:590)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:230)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:623)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:529)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:188)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:360)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
	at com.google.cloud.video.transcoder.v1beta1.stub.GrpcTranscoderServiceStub.create(GrpcTranscoderServiceStub.java:158)
	at com.google.cloud.video.transcoder.v1beta1.stub.TranscoderServiceStubSettings.createStub(TranscoderServiceStubSettings.java:277)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.<init>(TranscoderServiceClient.java:142)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.create(TranscoderServiceClient.java:123)
	at com.google.cloud.video.transcoder.v1beta1.TranscoderServiceClient.create(TranscoderServiceClient.java:114)
	at com.protonn.googletranscoder.CreateJobWithStaticOverlay.createJobWithStaticOverlay(CreateJobWithStaticOverlay.java:37)
	at com.protonn.googletranscoder.CreateJobWithStaticOverlay.main(CreateJobWithStaticOverlay.java:28)
13:33:57.273 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - io_grpc_netty_shaded_netty_tcnative_osx_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /var/folders/8l/_7qky9cj38z5s8fzxxxs2ctr0000gn/T
java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path: [/Users/aditya/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
```
OS : Mac BigSur 11.1 (M1 chip)

**Comment by nwbirnie** [comment]
It's likely that you have a version conflict with the netty libraries being loaded. Can you check your project's dependencies with `/gradlew dependencies --configuration runtimeClasspath`? Look for the versoins of `io.grpc` artifacts - they should all be the same.

**Comment by nwbirnie** [comment]
If you include the version of the library that you're using I can give you the expected version for these.

**Comment by aditya-protonn** [comment]
aditya@Adityas-MBP ProtonnApi % ./gradlew protonn:dependencies |grep 'io.grpc'

|    |    |    |    |    \--- io.grpc:grpc-context:1.27.2 -> 1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-core:1.36.0
|    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-api:1.36.0
|    |    +--- io.grpc:grpc-auth:1.36.0
|    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    +--- io.grpc:grpc-alts:1.36.0
|    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    +--- io.grpc:grpc-stub:1.36.0
|    +--- io.grpc:grpc-context:1.36.0 (c)
|    +--- io.grpc:grpc-core:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf-lite:1.36.0 (c)
|    +--- io.grpc:grpc-api:1.36.0 (c)
|    +--- io.grpc:grpc-auth:1.36.0 (c)
|    +--- io.grpc:grpc-netty-shaded:1.36.0 (c)
|    +--- io.grpc:grpc-alts:1.36.0 (c)
|    +--- io.grpc:grpc-grpclb:1.36.0 (c)
|    +--- io.grpc:grpc-stub:1.36.0 (c)
|    |    |    +--- io.grpc:grpc-api:1.36.0
|    |    |    +--- io.grpc:grpc-context:1.36.0
|    |    |    +--- io.grpc:grpc-stub:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    |    +--- io.grpc:grpc-auth:1.36.0
|    |    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    |    +--- io.grpc:grpc-alts:1.36.0
|    |    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    |    +--- io.grpc:grpc-core:1.36.0
|              |    |    |    \--- io.grpc:grpc-context:1.27.2 -> 1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-core:1.36.0
|    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-api:1.36.0
|    |    +--- io.grpc:grpc-auth:1.36.0
|    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    +--- io.grpc:grpc-alts:1.36.0
|    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    +--- io.grpc:grpc-stub:1.36.0
|    +--- io.grpc:grpc-context:1.36.0 (c)
|    +--- io.grpc:grpc-core:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf-lite:1.36.0 (c)
|    +--- io.grpc:grpc-api:1.36.0 (c)
|    +--- io.grpc:grpc-auth:1.36.0 (c)
|    +--- io.grpc:grpc-netty-shaded:1.36.0 (c)
|    +--- io.grpc:grpc-alts:1.36.0 (c)
|    +--- io.grpc:grpc-grpclb:1.36.0 (c)
|    +--- io.grpc:grpc-stub:1.36.0 (c)
|    |    |    +--- io.grpc:grpc-api:1.36.0
|    |    |    +--- io.grpc:grpc-context:1.36.0
|    |    |    +--- io.grpc:grpc-stub:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    |    +--- io.grpc:grpc-auth:1.36.0
|    |    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    |    +--- io.grpc:grpc-alts:1.36.0
|    |    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    |    +--- io.grpc:grpc-core:1.36.0
|              |    |    |    \--- io.grpc:grpc-context:1.27.2 -> 1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-core:1.36.0
|    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-api:1.36.0
|    |    +--- io.grpc:grpc-auth:1.36.0
|    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    +--- io.grpc:grpc-alts:1.36.0
|    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    +--- io.grpc:grpc-stub:1.36.0
|    +--- io.grpc:grpc-context:1.36.0 (c)
|    +--- io.grpc:grpc-core:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf-lite:1.36.0 (c)
|    +--- io.grpc:grpc-api:1.36.0 (c)
|    +--- io.grpc:grpc-auth:1.36.0 (c)
|    +--- io.grpc:grpc-netty-shaded:1.36.0 (c)
|    +--- io.grpc:grpc-alts:1.36.0 (c)
|    +--- io.grpc:grpc-grpclb:1.36.0 (c)
|    +--- io.grpc:grpc-stub:1.36.0 (c)
|    |    |    +--- io.grpc:grpc-api:1.36.0
|    |    |    +--- io.grpc:grpc-context:1.36.0
|    |    |    +--- io.grpc:grpc-stub:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    |    +--- io.grpc:grpc-auth:1.36.0
|    |    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    |    +--- io.grpc:grpc-alts:1.36.0
|    |    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    |    +--- io.grpc:grpc-core:1.36.0
|    |    |    |    |    \--- io.grpc:grpc-context:1.27.2 -> 1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-core:1.36.0
|    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-api:1.36.0
|    |    +--- io.grpc:grpc-auth:1.36.0
|    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    +--- io.grpc:grpc-alts:1.36.0
|    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    +--- io.grpc:grpc-stub:1.36.0
|    +--- io.grpc:grpc-context:1.36.0 (c)
|    +--- io.grpc:grpc-core:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf-lite:1.36.0 (c)
|    +--- io.grpc:grpc-api:1.36.0 (c)
|    +--- io.grpc:grpc-auth:1.36.0 (c)
|    +--- io.grpc:grpc-netty-shaded:1.36.0 (c)
|    +--- io.grpc:grpc-alts:1.36.0 (c)
|    +--- io.grpc:grpc-grpclb:1.36.0 (c)
|    +--- io.grpc:grpc-stub:1.36.0 (c)
|    |    |    +--- io.grpc:grpc-api:1.36.0
|    |    |    +--- io.grpc:grpc-context:1.36.0
|    |    |    +--- io.grpc:grpc-stub:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    |    +--- io.grpc:grpc-auth:1.36.0
|    |    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    |    +--- io.grpc:grpc-alts:1.36.0
|    |    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    |    +--- io.grpc:grpc-core:1.36.0
|              |    |    |    \--- io.grpc:grpc-context:1.27.2 -> 1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-core:1.36.0
|    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    +--- io.grpc:grpc-context:1.36.0
|    |    +--- io.grpc:grpc-api:1.36.0
|    |    +--- io.grpc:grpc-auth:1.36.0
|    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    +--- io.grpc:grpc-alts:1.36.0
|    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    +--- io.grpc:grpc-stub:1.36.0
|    +--- io.grpc:grpc-context:1.36.0 (c)
|    +--- io.grpc:grpc-core:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf:1.36.0 (c)
|    +--- io.grpc:grpc-protobuf-lite:1.36.0 (c)
|    +--- io.grpc:grpc-api:1.36.0 (c)
|    +--- io.grpc:grpc-auth:1.36.0 (c)
|    +--- io.grpc:grpc-netty-shaded:1.36.0 (c)
|    +--- io.grpc:grpc-alts:1.36.0 (c)
|    +--- io.grpc:grpc-grpclb:1.36.0 (c)
|    +--- io.grpc:grpc-stub:1.36.0 (c)
|    |    |    +--- io.grpc:grpc-api:1.36.0
|    |    |    +--- io.grpc:grpc-context:1.36.0
|    |    |    +--- io.grpc:grpc-stub:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf:1.36.0
|    |    |    +--- io.grpc:grpc-protobuf-lite:1.36.0
|    |    |    +--- io.grpc:grpc-auth:1.36.0
|    |    |    +--- io.grpc:grpc-netty-shaded:1.36.0
|    |    |    +--- io.grpc:grpc-alts:1.36.0
|    |    |    +--- io.grpc:grpc-grpclb:1.36.0
|    |    |    +--- io.grpc:grpc-core:1.36.0

**Comment by nwbirnie** [comment]
Which version of `google-ads` are you using?

**Comment by nwbirnie** [comment]
Next thing to check (assuming 1.36.0 is supported by the client library) would be all the `gax` modules in `com.google.api` are consistent with each other and with grpc.

**Comment by nwbirnie** [comment]
Closing due to no activity. Please let us know if we can be of assistance.
