### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: com/google/api/gax/rpc/mtls/MtlsProvider 

### ISSUE THREAD

**Issue by fbuitron** [googleads/google-ads-java#481]
Hello,

I am getting the following error:

```
 java.lang.NoClassDefFoundError: com/google/api/gax/rpc/mtls/MtlsProvider
 at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$Builder.<init>(InstantiatingGrpcChannelProvider.java:412)
at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$Builder.<init>(InstantiatingGrpcChannelProvider.java:406)
at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.newBuilder(InstantiatingGrpcChannelProvider.java:403)
at com.google.ads.googleads.lib.GoogleAdsClient.newBuilder(GoogleAdsClient.java:83)
```

When trying to do:
`GoogleAdsClient.newBuilder()`

It looks like a dependency conflict. I added the following in the `dependencyManagement` section of my pom.xml, but still no luck.
```
<dependency>
   <groupId>com.google.api</groupId>
   <artifactId>gax</artifactId>
   <version>1.50.1</version>
</dependency>
```

Do you have any idea how can I fix this problem?

Here is the tree of dependencies that are interesting for this library

```
\- com.google.api-ads:google-ads:jar:15.0.0:runtime
[INFO] |     +- com.google.api:gax:jar:1.50.1:runtime (version managed from 1.65.1)
[INFO] |     |  +- (com.google.guava:guava:jar:26.0-android:compile - version managed from 20.0; scope updated from runtime; omitted for duplicate)
[INFO] |     |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:compile - scope updated from runtime; omitted for duplicate)
[INFO] |     |  +- org.threeten:threetenbp:jar:1.3.3:runtime
[INFO] |     |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.22.2:runtime (version managed from 0.18.0)
[INFO] |     |  |  +- com.google.auto.value:auto-value-annotations:jar:1.7.4:runtime
[INFO] |     |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  |  +- (com.google.auth:google-auth-library-credentials:jar:0.22.2:runtime - version managed from 0.24.0; omitted for duplicate)
[INFO] |     |  |  +- (com.google.http-client:google-http-client:jar:1.38.0:compile - scope updated from runtime; omitted for duplicate)
[INFO] |     |  |  +- (com.google.http-client:google-http-client-jackson2:jar:1.38.0:compile - scope updated from runtime; omitted for duplicate)
[INFO] |     |  |  \- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  +- com.google.api:api-common:jar:1.8.1:runtime
[INFO] |     |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |  \- (javax.annotation:javax.annotation-api:jar:1.3.2:runtime - omitted for duplicate)
[INFO] |     |  \- io.opencensus:opencensus-api:jar:0.24.0:runtime
[INFO] |     |     \- io.grpc:grpc-context:jar:1.37.0:runtime (version managed from 1.22.1)
[INFO] |     +- com.google.api:gax-grpc:jar:1.65.1:runtime
[INFO] |     |  +- (com.google.api:gax:jar:1.50.1:runtime - version managed from 1.65.1; omitted for duplicate)
[INFO] |     |  +- io.grpc:grpc-stub:jar:1.37.0:runtime
[INFO] |     |  |  +- io.grpc:grpc-api:jar:1.37.0:runtime
[INFO] |     |  |  |  +- (io.grpc:grpc-context:jar:1.37.0:runtime - version managed from 1.22.1; omitted for duplicate)
[INFO] |     |  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  |  |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |  |  |  \- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |  |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |  |  +- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |  |  \- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  +- io.grpc:grpc-auth:jar:1.37.0:runtime
[INFO] |     |  |  +- (io.grpc:grpc-api:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |  |  +- (com.google.auth:google-auth-library-credentials:jar:0.22.2:runtime - omitted for duplicate)
[INFO] |     |  |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |  |  +- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  |  +- (io.grpc:grpc-context:jar:1.37.0:runtime - version managed from 1.22.1; omitted for duplicate)
[INFO] |     |  |  \- (io.opencensus:opencensus-api:jar:0.28.0:runtime - omitted for conflict with 0.24.0)
[INFO] |     |  +- io.grpc:grpc-protobuf:jar:1.37.0:runtime
[INFO] |     |  |  +- (io.grpc:grpc-api:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  |  +- (com.google.protobuf:protobuf-java:jar:3.12.0:runtime - version managed from 2.6.0; omitted for duplicate)
[INFO] |     |  |  +- (com.google.api.grpc:proto-google-common-protos:jar:2.0.1:runtime - omitted for duplicate)
[INFO] |     |  |  +- io.grpc:grpc-protobuf-lite:jar:1.37.0:runtime
[INFO] |     |  |  |  +- (io.grpc:grpc-api:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |  |  |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  |  |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |  |  |  \- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |  |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |  +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |  |  \- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.1-android; omitted for duplicate)
[INFO] |     |  +- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  +- (org.threeten:threetenbp:jar:1.5.0:runtime - omitted for conflict with 1.3.3)
[INFO] |     |  +- (com.google.auth:google-auth-library-oauth2-http:jar:0.22.2:runtime - version managed from 0.24.0; omitted for duplicate)
[INFO] |     |  +- com.google.auth:google-auth-library-credentials:jar:0.22.2:runtime
[INFO] |     |  +- com.google.api.grpc:proto-google-common-protos:jar:2.0.1:runtime
[INFO] |     |  |  \- (com.google.protobuf:protobuf-java:jar:3.12.0:runtime - version managed from 3.13.0; omitted for duplicate)
[INFO] |     |  +- (com.google.api:api-common:jar:1.10.1:runtime - omitted for conflict with 1.8.1)
[INFO] |     |  +- io.grpc:grpc-netty-shaded:jar:1.37.0:runtime
[INFO] |     |  |  \- io.grpc:grpc-core:jar:1.37.0:runtime
[INFO] |     |  |     +- (io.grpc:grpc-api:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |  |     +- com.google.code.gson:gson:jar:2.8.6:runtime
[INFO] |     |  |     +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |     |  |     +- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |  |     +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |  |     +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  |     +- io.perfmark:perfmark-api:jar:0.23.0:runtime
[INFO] |     |  |     \- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |  \- io.grpc:grpc-alts:jar:1.37.0:runtime
[INFO] |     |     +- (io.grpc:grpc-auth:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |     +- io.grpc:grpc-grpclb:jar:1.37.0:runtime
[INFO] |     |     |  +- (io.grpc:grpc-core:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |     |  +- (io.grpc:grpc-protobuf:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |     |  +- (io.grpc:grpc-stub:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |     |  +- (com.google.protobuf:protobuf-java:jar:3.12.0:runtime - version managed from 3.13.0; omitted for duplicate)
[INFO] |     |     |  +- com.google.protobuf:protobuf-java-util:jar:3.12.0:runtime
[INFO] |     |     |  |  +- (com.google.protobuf:protobuf-java:jar:3.12.0:runtime - version managed from 3.13.0; omitted for duplicate)
[INFO] |     |     |  |  \- (com.google.code.gson:gson:jar:2.8.6:runtime - omitted for duplicate)
[INFO] |     |     |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |     |  +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |     |  +- (org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime - omitted for conflict with 1.14)
[INFO] |     |     |  \- (com.google.code.findbugs:jsr305:jar:3.0.2:runtime - omitted for duplicate)
[INFO] |     |     +- (io.grpc:grpc-protobuf:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |     +- (io.grpc:grpc-stub:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     |     +- (com.google.protobuf:protobuf-java:jar:3.12.0:runtime - version managed from 3.13.0; omitted for duplicate)
[INFO] |     |     +- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.1:runtime
[INFO] |     |     +- (com.google.auth:google-auth-library-oauth2-http:jar:0.22.2:runtime - version managed from 0.24.0; omitted for duplicate)
[INFO] |     |     +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |     +- (com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime - version managed from 2.1.3; omitted for duplicate)
[INFO] |     |     \- (io.grpc:grpc-netty-shaded:jar:1.37.0:runtime - omitted for duplicate)
[INFO] |     +- io.netty:netty-tcnative-boringssl-static:jar:2.0.26.Final:runtime
[INFO] |     +- (org.slf4j:slf4j-api:jar:1.7.25:runtime - version managed from 1.7.21; omitted for duplicate)
[INFO] |     +- com.google.api-ads:google-ads-annotation-processing:jar:15.0.0:runtime
[INFO] |     |  +- com.squareup:javapoet:jar:1.11.1:runtime
[INFO] |     |  +- (com.google.api:gax:jar:1.50.1:runtime - version managed from 1.65.1; omitted for duplicate)
[INFO] |     |  +- (com.google.guava:guava:jar:26.0-android:runtime - version managed from 30.0-android; omitted for duplicate)
[INFO] |     |  \- (javax.annotation:javax.annotation-api:jar:1.3.2:runtime - omitted for duplicate)
[INFO] |     \- javax.annotation:javax.annotation-api:jar:1.3.2:runtime
```

Any suggestion is greatly appreciated.

**Comment by nwbirnie** [comment]
MtlsProvider was [added to GAX](https://github.com/googleapis/gax-java/commits/master/gax/src/main/java/com/google/api/gax/rpc/mtls/MtlsProvider.java) in [1.65.0](https://github.com/googleapis/gax-java/releases/tag/v1.65.0). We've tested the library with 1.65.1. Please could you try that version?

**Comment by fbuitron** [comment]
Thank you very much for the rapid response.

With this version in the `<DependencyManagement>` section it worked.

Closing the issue.
