### ISSUE TITLE
NoSuchMethodException when calling ListingGroupInfo.toString()

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#492]
**Describe the bug:**
I wanted to have an overview over the data that's stored in ListingGroupInfo. I did the following Gaql-Request via google.ads.googleads.v8.services.GoogleAdsService/SearchStream for an account containing Shopping-AdGroups:
```
SELECT customer.id,
       campaign.id,
       campaign.name,
       ad_group.id,
       ad_group.name,
       ad_group_criterion.criterion_id,
       ad_group_criterion.negative,
       ad_group_criterion.cpc_bid_micros,
       ad_group_criterion.url_custom_parameters,
       ad_group_criterion.listing_group.case_value.product_bidding_category.country_code,
       ad_group_criterion.listing_group.case_value.product_bidding_category.id,
       ad_group_criterion.listing_group.case_value.product_bidding_category.level,
       ad_group_criterion.listing_group.case_value.product_brand.value,
       ad_group_criterion.listing_group.case_value.product_channel.channel,
       ad_group_criterion.listing_group.case_value.product_channel_exclusivity.channel_exclusivity,
       ad_group_criterion.listing_group.case_value.product_condition.condition,
       ad_group_criterion.listing_group.case_value.product_custom_attribute.index,
       ad_group_criterion.listing_group.case_value.product_custom_attribute.value,
       ad_group_criterion.listing_group.case_value.product_item_id.value,
       ad_group_criterion.listing_group.case_value.product_type.level,
       ad_group_criterion.listing_group.case_value.product_type.value,
       ad_group_criterion.listing_group.parent_ad_group_criterion,
       ad_group_criterion.listing_group.type
  FROM ad_group_criterion
 WHERE campaign.status != REMOVED
   AND ad_group.status != REMOVED
   AND ad_group_criterion.status != REMOVED
```
When I tried to print the ListingGroupInfo (`System.out.println(row.getAdGroupCriterion().getListingGroup());`) the following Exception was thrown:
```
java.lang.RuntimeException: Generated message class "com.google.ads.googleads.v8.common.ListingGroupInfo" missing method "getParentAdGroupCriterionCase".
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2164)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2222)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessageV3.java:2890)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1977)
	at com.google.ads.googleads.v8.common.ListingGroupInfo.internalGetFieldAccessorTable(ListingGroupInfo.java:111)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:344)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:334)
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:519)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintStream.println(PrintStream.java:897)
	...
Caused by: java.lang.NoSuchMethodException: com.google.ads.googleads.v8.common.ListingGroupInfo.getParentAdGroupCriterionCase()
	at java.base/java.lang.Class.getMethod(Class.java:2109)
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
	... 17 more
```
**Steps to Reproduce:**
request the mentioned report in a shopping account and try to call toString() on the result row(s).

**Expected behavior:**
No exception is thrown, instead a pretty formatted ListingGroupInfo is returned.

**Client library version and API version:**
Client library version: com.google.api-ads:google-ads:15.0.0
Google Ads API version: 8
JDK version: openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Request/Response Logs:**
the request itself was sucessful, just creating a readable format of the message failed.
14:33:06.436 [INFO] summary [Gax-2] [c.g.a.g.l.l.RequestLogger:157] : SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v8.services.GoogleAdsService/SearchStream, Endpoint: googleads.googleapis.com:443, CustomerID: REDACTED RequestID: gqH5x1bAjHnntR4O4j4elA, ResponseCode: OK, Fault: null.

**Comment by nwbirnie** [comment]
I tried to replicate this on my machine but it appears to be working in the 15.0.0 release.

I'm thinking that you might have the wrong version of protobuf on the classpath. Could you check that you have at least version `3.15.2` please? Running `gradle -q dependencies --configuration testRuntimeClasspath` or similar should do the trick.

**Comment by nwbirnie** [comment]
If not you can try adding ` implementation com.google.protobuf:protobuf-java:jar:3.15.2` as a dependency of your project.
