### ISSUE TITLE
Error when requesting keyword_view: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#565]
Hi,

when doing this request
`SELECT customer.id, ad_group.id, ad_group_criterion.criterion_id, ad_group_criterion.url_custom_parameters, ad_group_criterion.keyword.text, ad_group_criterion.keyword.match_type, ad_group_criterion.final_urls, segments.date, metrics.clicks, metrics.cost_micros FROM keyword_view WHERE metrics.clicks > 0 AND segments.date BETWEEN '2022-02-13' AND '2022-02-14'`
for one specific account I get this exception 
```
Caused by: com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4769258
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:57)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:113)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
```

I think this is an extreme edge case - I do this request for some hundred accounts and it happens only at one single account. I haven't seen this error before, today 13:12 CET was the first time. The error occurs when using API v9 and v10 (I use google-ads 17.0.0). When I change the query to 
`SELECT ad_group_criterion.resource_name, ad_group_criterion.url_custom_parameters, ad_group_criterion.keyword.text, ad_group_criterion.keyword.match_type, ad_group_criterion.final_urls, segments.date, metrics.clicks, metrics.cost_micros FROM keyword_view WHERE metrics.clicks > 0 AND segments.date BETWEEN '2022-02-13' AND '2022-02-14'`
I get no error and the maximum of GoogleAdsRow.toByteArray().length is 497 bytes.

Unfortunately the logs don't contain a requestId, the RequestLogger only logs
`15:20:45.915 [WARN]  [grpc-default-executor-0] [c.g.a.g.l.l.RequestLogger:159] : FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v10.services.GoogleAdsService/SearchStream, Endpoint: googleads.googleapis.com:443, CustomerID: MY_CUSTOMER_ID, RequestID: null, ResponseCode: RESOURCE_EXHAUSTED, Fault: gRPC message exceeds maximum size 4194304: 4769258.`

Best regards,

Christian

**Comment by schabe77** [comment]
O.k., after this error now occurs for other accounts (and other reports) too, I took a closer look at it:
 - it only happens with google-ads:17.0.0, with google-ads:16.0.3 the problem doesn't occur
 - when I increase the default inbound message size (`serviceClient.searchStreamCallable().call(request, GrpcCallContext.createDefault().withCallOptions(CallOptions.DEFAULT.withMaxInboundMessageSize(10_000_000)));`) the error doesn't occur
 - when I save all result rows (`GoogleAdsRow.toByteArray()`) to a file the file sizes are the same, no mater if I use 16.0.3 or 17.0.0 (v9 as well as v10)

**Comment by an-tex** [comment]
We have the same issue since the update to 17.0.0

**Comment by jradcliff** [comment]
Thanks for reporting this. I suspect this may be related to changes in 17.0.0 to fix #174 , but I'll take a look.

-Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Are either of you doing anything "special" when creating a `GoogleAdsClient`, such as overriding headers or providing your own TransportChannelProvider? If so and you could share a snippet, that'd be very helpful in my investigation.

Thanks

**Comment by schabe77** [comment]
No, I don't do anything special. for the reports/searchStreams I only  add a custom timeout:
in the end I only do this
```
            GoogleAdsVersion.getLatestVersion()
                    .createGoogleAdsServiceClient()
                    .searchStreamCallable()
                    .call(request, GrpcCallContext.createDefault().withTimeout(READ_TIMEOUT));
```
That is also the place were I added `.withMaxInboundMessageSize(10_000_000)` to prevent the RESOURCE_EXHAUSTED error.

**Comment by an-tex** [comment]
Hi @jradcliff ,
thanks for the quick reply. Nope nothing special about `GoogleAdsClient`, here's the creation (scala code):
```scala
private val googleAdsClient = GoogleAdsClient.newBuilder()
  .setDeveloperToken("xxxx")
  .setCredentials(UserCredentials.newBuilder()
    .setClientId("xxxx")
    .setClientSecret("xxxx")
    .setRefreshToken("xxxx")
    .build()
  )
  .setLoginCustomerId(rootCustomerId)
  .build()
```

To me it seems the [default increase to 64MB](https://developers.google.com/google-ads/api/docs/best-practices/quotas) got lost.

**Comment by jradcliff** [comment]
Thank you both for providing those snippets, and @an-tex, you are 100% correct. I've got a PR out for review to address this.

**Comment by jradcliff** [comment]
I just released version 17.0.1 of the library a few minutes ago with a fix for this issue.

https://github.com/googleads/google-ads-java/releases/tag/17.0.1

It may take an hour or so for Maven repos to pick it up.

Thanks,
Josh

**Comment by an-tex** [comment]
Looking all good, thanks Josh!

**Comment by jradcliff** [comment]
Great! Thanks for confirming, and thanks again for helping to find the root cause.
