### ISSUE TITLE
Higher PAGE_SIZE value results in RejectedExecutionException

### ISSUE THREAD

**Issue by mohitmah** [googleads/google-ads-java#567]
**Describe the bug:**
I am calling the following method with different **PAGE_SIZE** values.

For PAGE_SIZE = 5000, 1000, 750 the below exception is thrown. When I set the PAGE_SIZE to 250, it doesn't result in such exception and works smoothly. In the SDK, it uses asynchronous mechanisms to fetch the result from server and client code is not aware of internal thread pools that are required to do that asynchronous processing. As such, client code receives RejectedExecutionException which is a symptom of threads not available to process request. It took us several trials to get to optimal PAGE_SIZE value. Can you suggest a way to choose the optimal PAGE_SIZE or any way to allow more threads to be created by client by providing some parameter during the asynchronous calls?

`BatchJobServiceClient.ListBatchJobResultsPagedResponse.iterateAll`

Code snippet:

```
        BatchJobServiceClient.ListBatchJobResultsPagedResponse response;
        List<BatchJobResult> results = Lists.newArrayList();
        try (BatchJobServiceClient batchJobServiceClient = googleAdsVersion.createBatchJobServiceClient()) {
            ListBatchJobResultsRequest listBatchJobResultsRequest = ListBatchJobResultsRequest
                    .newBuilder()
                    .setPageSize(PAGE_SIZE)
                    .setResourceName(ResourceNames.batchJob(customerId, jobId))
                    .setResponseContentType(ResponseContentTypeEnum.ResponseContentType.MUTABLE_RESOURCE)
                    .build();
            response = batchJobServiceClient.listBatchJobResults(listBatchJobResultsRequest);

            Iterable<BatchJobServiceClient.ListBatchJobResultsPage> pages = response.iteratePages();

            for (BatchJobServiceClient.ListBatchJobResultsPage page : pages) {
                ListBatchJobResultsResponse pagedResponse = page.getResponse();
                if (pagedResponse != null) {
                    results.addAll(pagedResponse.getResultsList());
                } else {
                    log.error("Paged response is null {}", response);
                }
            }
        } catch (GoogleAdsException e) {
            log.error("some message", e);
            return new ArrayList<>();
        }

```
**Steps to Reproduce:**

1. Upload 5000 operations to Google using BatchJobService
1. Execute the code snippet with PAGE_SIZE = 5000 and collect the result of BatchJobServiceClient.ListBatchJobResultsPagedResponse.iterateAll into a List

**Expected behavior:**
1. It will result in RejectedExecutionException with PAGE_SIZE = 5000 but won't result in such exception if PAGE_SIZE = 250 or below.

**Client library version and API version:**
Client library version: https://repo.maven.apache.org/maven2/com/google/api-ads/google-ads-shadowjar/0.0.1-alpha/
Google Ads API version: v8
JDK version: JDK8

**Request/Response Logs:**
14 Feb 2022 18:15:17,972 [INFO]  (Gax-526)       com.google.ads.googleads.lib.request.summary: SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v8.services.BatchJobService/ListBatchJobResults, Endpoint: [googleads.googleapis.com:443](http://googleads.googleapis.com:443/), CustomerID: customers/<REDACTED>/batchJobs/[8157010607](tel:(815)%20701-0607), RequestID: gpBQhVWwk8tUr2g5GTHHTw, ResponseCode: OK, Fault: null.

Response:
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@14d9ece0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@43193428[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]

        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)

        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)

        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)

        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)

        at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)

        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)

        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)

        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:747)

        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:683)

        at io.grpc.internal.FailingClientStream.start(FailingClientStream.java:54)

        at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:283)

        at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:188)

        at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)

        at com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:94)

        at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)

        at com.google.ads.googleads.lib.logging.LoggingInterceptor$1.start(LoggingInterceptor.java:76)

        at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332)

        at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:306)

        at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:218)

        at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)

        at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65)

        at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)

        at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87)

        at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)

        at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)

        at com.google.ads.googleads.lib.callables.ExceptionTransformingUnaryCallable.futureCall(ExceptionTransformingUnaryCallable.java:49)

        at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)

        at com.google.api.gax.paging.AbstractPage.callApi(AbstractPage.java:128)

        at com.google.api.gax.paging.AbstractPage.getNextPageImpl(AbstractPage.java:118)

        at com.google.api.gax.paging.AbstractPage.getNextPage(AbstractPage.java:91)

        at com.google.api.gax.paging.AbstractPage$AllResourcesIterator.computeNext(AbstractPage.java:177)

        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)

        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)

        at com.google.api.client.util.Lists.newArrayList(Lists.java:73)

        at com.google.api.client.util.Lists.newArrayList(Lists.java:61)
```
 
**Anything else we should know about your project / environment:**

**Comment by mohitmah** [comment]
This is all the stack trace that I have. Not sure of the root cause of the error. It has something to do with multi threading in the SDK. I get that the server is responding with OK status but the SDK that converts the server response is having some trouble. It works well when PAGE_SIZE is set to 250 or less but doesn't work with higher PAGE_SIZE

**Comment by jradcliff** [comment]
Do you have detailed logging enabled (`com.google.ads.googleads.lib.request.detail` level set to `debug`) as described at https://developers.google.com/google-ads/api/docs/client-libs/java/logging? If you're using our [log4j2.xml sample file](https://github.com/googleads/google-ads-java/blob/main/google-ads-examples/src/main/resources/log4j2.xml), that would look like this:

```
<Logger name="com.google.ads.googleads.lib.request.detail" level="debug"/>
```

If so, please try changing that to `info` and let me know if that makes a difference.

I suspect that the issue is that with the `MUTABLE_RESOURCE` response type, the response is quite large, and while you are allocating a large amount of memory, if other processes in your thread pool are also memory-intensive, you'll run out of heap space.

**Comment by jradcliff** [comment]
Hi,

Were you able to look into the logging question? Or did you find a different root cause?

Thanks

**Comment by jradcliff** [comment]
Hi,

I think we may have found the source of this issue. @devchas or I will provide an update once we've confirmed.

Cheers,
Josh

**Comment by devchas** [comment]
Hi @mohitmah 

**What is causing this behavior?**

After some investigation, it seems like the root cause of the problem is that the service client you created to retrieve the batch job results is being closed before the Google API server is done returning results. As you can see from the logs, you're getting a SUCCESS returned from the server. However, the request fails in calls to get the results from subsequent pages of the response. You can see in the 6th line from the bottom of your stack trace, there is an issue getting the next page.

**Why is this happening?**

The service client can be closed for a number of reasons. For example, this can be done by calling `close()` explicitly. More likely what is happening is that the code making the API request is outside the scope of the try block that creates the service client. Once the code inside the try block that creates the service client is done executing, the service client will be automatically closed, and you will no longer be able to complete the request. 

For example, I was able to recreate your issue by creating a service client inside of a try block in the main thread, then executing the API call in a separate, non-blocking thread. In my example, the code in the try block of the main thread completed before the API call completed in the second thread, so the service client was closed before all pages were returned. This effectively creates a race condition between the code in the try block and the code making the API request, which may explain why your API request was only successful with smaller page sizes. 

It is difficult to tell exactly where or why your service client is being closed without seeing the complete code, but I believe this is the underlying cause of your issue. Hopefully, this will point you in the right direction to make the fix in your code. Please let us know if you're able to find a resolution with this information.

**Comment by mohitmah** [comment]
Hi,

We have switched to a lower PAGE_SIZE value (250) and refactored some code to move the client initiation in a try with resources block instead of explicitly calling the close method on the client. This solved the issue for us.

**Comment by mohitmah** [comment]
Feel free to close it
