### ISSUE TITLE
DeadlineExceededException when sending a request 

### ISSUE THREAD

**Issue by mesara** [googleads/google-ads-java#578]
Hi 

I am sending a request to get the labels of a group of accounts however, after sending the first request it is timing out due to DeadlineExceededException (after 60 minutes). This is happening only on a server, in a local environment is running without issue. 

This is the query I'm sending

query: "SELECT label.name FROM label where label.status = \'ENABLED\'"

Exception: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 3599.612457670s

Do you what I'm missing here?

Thanks in advance

**Comment by jradcliff** [comment]
Hi,

Could you try enabling `DEBUG` logging as described in our [Logging guide](https://developers.google.com/google-ads/api/docs/client-libs/java/logging#logging_layout_and_functionality)? I'm curious if there are any retries or other issues occurring behind the scenes.

Thanks,
Josh

**Comment by mesara** [comment]
Hi @jradcliff thanks, I'll enable DEBUG logging. In the meantime I leave here some other logs I found with {"methodName":"rejectedExecution","fileName":"ThreadPoolExecutor.java","lineNumber":2047,"className":"java.util.concurrent.ThreadPoolExecutor$AbortPolicy","nativeMethod":false}

[logs.log](https://github.com/googleads/google-ads-java/files/8127592/logs.log)

**Comment by mesara** [comment]
Hi @jradcliff I got the following logs:

Failure message: null
Status: Status{code=OK, description=null, cause=null}.
00:04:26.984 [grpc-nio-worker-ELG-1-4] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0xfa2fa5e1, L:/192.168.0.164:60069 - R:googleads.googleapis.com/74.125.193.95:443] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
00:04:26.991 [grpc-default-executor-0] WARN com.google.ads.googleads.lib.logging.LoggingInterceptor - Failed to log request.
java.lang.NullPointerException: null
	at com.google.ads.googleads.lib.logging.LoggingInterceptor.getCustomerId(LoggingInterceptor.java:158)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor.logSummary(LoggingInterceptor.java:236)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor.access$400(LoggingInterceptor.java:42)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:95)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I noticed that if I set the page size to x number, while iterating after reaching the x number it throws the exception

**Comment by jradcliff** [comment]
Hi,

Could you share the code you're using to iterate over the results?

Thanks

**Comment by mesara** [comment]
Hi,

This is the piece of code

**Comment by mesara** [comment]
I changed the way I was creating the GoogleAdsServiceClient because I think there were many creations of it. Now at the moment I don't see the error anymore. But please let me know if you see something off in my code.

**Comment by jradcliff** [comment]
Hi,

Glad to hear you don't see errors anymore. The code you shared looks correct to me.

One thing to keep in mind is that if you are using the same service client (such as `GoogleAdsServiceClient`, `CampaignServiceClient`, etc.) for multiple requests, make sure that you only close the service client after you've completed all of the requests you want to make with that service client. For example, in the snippet you provided, the service client `googleAdsServiceClient` will be implicitly closed when the code leaves the try-with-resources block. If you tried to use that service client for requests after that, you'll encounter errors such as a `RejectedExecutionException`.

Thanks,
Josh
