### ISSUE TITLE
Migrating from the AdWords API to the Google Ads API - Error: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found.

### ISSUE THREAD

**Issue by YospaDavis** [googleads/google-ads-java#580]
Error when running my jar:

Running my project locally in itellij works fine, But when trying to run a executable jar I created I get the following error:
Exception in thread "main" io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
I tried adding all those libraries but it didn't help.

trace-
        at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:43)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:348)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1900(InstantiatingGrpcChannelProvider.java:82)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:239)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:249)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:227)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:205)
        at com.google.ads.googleads.v10.services.stub.GrpcConversionAdjustmentUploadServiceStub.create(GrpcConversionAdjustmentUploadServiceStub.java:69)
        at com.google.ads.googleads.v10.services.stub.ConversionAdjustmentUploadServiceStubSettings.createStub(ConversionAdjustmentUploadServiceStubSettings.java:101)
        at com.google.ads.googleads.v10.services.ConversionAdjustmentUploadServiceClient.<init>(ConversionAdjustmentUploadServiceClient.java:137)
        at com.google.ads.googleads.v10.services.ConversionAdjustmentUploadServiceClient.create(ConversionAdjustmentUploadServiceClient.java:114)
        at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V10Client.createConversionAdjustmentUploadServiceClient(GeneratedCatalog.java:5279)
        at scala.services.GoogleAdsUtils$.uploadAdjustments(GoogleAdsUtils.scala:52)
        at scala.ProcessUploadAdjustments$.uploadConversions(ProcessUploadAdjustments.scala:22)
        at scala.UploadApp$.doUpload(UploadApp.scala:11)
        at scala.UploadApp$.delayedEndpoint$scala$UploadApp$1(UploadApp.scala:21)
        at scala.UploadApp$delayedInit$body.apply(UploadApp.scala:6)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at scala.UploadApp$.main(UploadApp.scala:6)
        at scala.UploadApp.main(UploadApp.scala)

Client library version: 17.0.1
Google Ads API version 10
JDK version: 1.8.0_231

Thank you

**Comment by blueJupiter16** [comment]
Facing something similar. Have elaborated in this StackOverflow post:
https://stackoverflow.com/questions/71322912/java-lang-verifyerror-operand-stack-overflow-for-google-ads-api-and-sbt

**Comment by jradcliff** [comment]
Hi,

Have you checked the dependencies of your project using `mvn dependency:tree` (if using Maven) or `gradle dependencies` (if using Gradle)? I'd be curious to see which `protobuf` and `grpc` dependencies are in that list.

Note that we do offer a shaded jar via the `com.google.api-ads:google-ads-shadowjar` artifact. You could try depending on that instead to see if that resolves the issue.

Thanks,
Josh

**Comment by YospaDavis** [comment]
I solved the issue.
I am using sbt, with an assembly plugin, I changed it like this and it worked:
```
assemblyMergeStrategy in assembly := {
  case x if x.contains("io.netty.versions.properties") => MergeStrategy.discard
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}
```

**Comment by blueJupiter16** [comment]
Solved this by using the `google-ads-shadowjar` as an external jar rather than a dependency.
.
@jradcliff Can we add the shadow-jar information in the google-ads documentation? I wasn't aware of this. Maybe it can help others save some time.

**Comment by jradcliff** [comment]
@blueJupiter16 , totally agree this should go in our docs. I actually filed a docs issue for myself yesterday when I realized it was missing there. I'll take care of that shortly.

Glad to hear you both were able to resolve this. I'll mark this issue closed.

**Comment by jradcliff** [comment]
FYI, I just added this to the [Advanced usage page](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#shadow_dependencies) of our documentation.

Cheers,
Josh
