### ISSUE TITLE
ServerStream closure issue

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/google-ads-java#611]
We are using ServerStream<SearchGoogleAdsStreamResponse> to get response from Google Ads API call. Is there any way to close the server stream to avoid memory leaks  as we are getting below error while running the reports in server.

 Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f6a71cb2000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
[thread 140095153448704 also had an error]
Exception in thread "Gax-30410" java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jradcliff** [comment]
Hi,

Please see my [response to a similar issue](https://github.com/googleads/google-ads-java/issues/602#issuecomment-1090296689). In addition, make sure that you are closing your service client (`GoogleAdsServiceClient`) as mentioned in the second paragraph of [our guide](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#service_client_reuse).

If those don't resolve the memory issues, let me know.

Thanks,
Josh

**Comment by jradcliff** [comment]
Please see my response in #612 as well.

Thanks
