### ISSUE TITLE
Google Ads  Java library java.lang.IllegalAccessError (com.google.protobuf.AbstractMessage.memoizedSize)

### ISSUE THREAD

**Issue by Girishyc** [googleads/google-ads-java#615]
We are working on google ads connector but getting the following runtime exception.

`
**Exception location :** 

SearchGoogleAdsStreamRequest request =SearchGoogleAdsStreamRequest.newBuilder()
			                                          .setCustomerId(config.getClientCustomerId().replace("-", ""))
			                                          .setQuery(query)
			                                          .build();

**Runtime Exception :** 

Exception in thread "grpc-default-executor-0" java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class com.google.ads.googleads.v9.services.SearchGoogleAdsStreamRequest
        at com.google.ads.googleads.v9.services.SearchGoogleAdsStreamRequest.getSerializedSize(SearchGoogleAdsStreamRequest.java:259)
        at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
        at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
        at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
        at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
        at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
        at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
        at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
        at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
        at io.grpc.internal.MetadataApplierImpl.finalizeWith(MetadataApplierImpl.java:110)
        at io.grpc.internal.MetadataApplierImpl.apply(MetadataApplierImpl.java:78)
        at io.grpc.CallCredentials2$1.apply(CallCredentials2.java:61)
        at io.grpc.auth.GoogleAuthLibraryCallCredentials$1.onSuccess(GoogleAuthLibraryCallCredentials.java:133)
        at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:549)
        at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:540)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1237)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:141)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:130)
        at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:88)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
        at java.util.concurrent.FutureTask.set(FutureTask.java:233)
        at java.util.concurrent.FutureTask.run(FutureTask.java:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748) `
       
We have also tried the same request using **SearchGoogleAdsRequest** but getting the same runtime exception. 

We are using **google-ads-16.0.0.jar** java library for our connector development.

**Java installation detail.**

openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

Any kind of help would be greatly appreciated in debugging this issue.

**Comment by jradcliff** [comment]
Hi,

Could you check if you have other dependencies that are pulling in protobuf (`com.google.protobuf:protobuf-java`)? It appears that's the case, but you can check as follows.

- If using maven: `mvn dependency:tree`
- If using gradle: `./gradlew -q dependencies --configuration=runtimeClasspath`

Thanks,
Josh

**Comment by Girishyc** [comment]
@jradcliff Unfortunately we don't use gradle or maven. But here is the list of pro related jars which are also in our project class path.

1. opencensus-proto-0.2.0.jar
2. proto-google-common-protos-2.4.1.jar
3. proto-google-iam-v1-0.1.28.jar
4. protobuf-java-3.18.1.jar
5. protobuf-java-util-3.17.2.jar
6. grpc-protobuf-1.41.0.jar
7. grpc-protobuf-lite-1.41.0.jar

We have also tried to remove above jars from our class path but still getting the same exception when we deploy this to our dev servers. Same setup works just fine when we run project in eclipse on our local dev machines.

**Comment by jradcliff** [comment]
You could detect which JAR file is loading protobuf classes by adding `-verbose:class` to your `java` command. This will produce a _large_ amount of output, but it will tell you, for example, which JAR file is being used to load `com.google.protobuf.AbstractMessage`. I suspect it will be one of items 1-3 from your list, and that you'll find that one of those JARs is causing the JVM to pull in an old protobuf JAR.

**Comment by jradcliff** [comment]
Closing this since there haven't been any updates, but feel free to reopen if you still encounter issues.

Thanks
