### ISSUE TITLE
Task was cancelled Exception when polling results

### ISSUE THREAD

**Issue by OUWANG** [googleads/google-ads-java#622]
Since May 4th, we started to see exceptions below when retrieving/polling the bid results from the API, preventing us from making changes to the bid values. We provided the request log and the conclusion from Google support was `it appears the job took 5 minutes and finished the same time you got your error`, and we were advised to open an issue for the client specific library.

Can you tell us why the request would be cancelled? Below is the exception message:

```
[2022-05-10 09:33:21,395] INFO - java.util.concurrent.CancellationException: Task was cancelled.
[2022-05-10 09:33:21,395] INFO - 	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1496)
[2022-05-10 09:33:21,395] INFO - 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:586)
[2022-05-10 09:33:21,395] INFO - 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:463)
[2022-05-10 09:33:21,395] INFO - 	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:100)
[2022-05-10 09:33:21,395] INFO - 	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:73)
[2022-05-10 09:33:21,395] INFO - 	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:133)
```

**Comment by OUWANG** [comment]
Hi Josh,

Confirming this was for batch job ID `9060205640`. The timeout we’re using for the `OperationFuture.get(long, TimeUnit)` call is 20 minutes and we were seeing the cancellation after about 3-5 minutes. We also checked and we are not calling `OperationFuture.get()` after closing the `BatchJobServiceClient` either implicitly or using try-with-resources block.

What were the dates that you had this issue that got fixed regarding the long running batch jobs?

Thanks,
Austin

**Comment by jradcliff** [comment]
Hi Austin,

Some users reported seeing issues starting on May 4, and the fix I mentioned went into place yesterday (May 11).

I suspect that your canceled job was a side effect of the issue that was fixed. Could you let me know if you're continuing to see this problem?

Thanks,
Josh

**Comment by OUWANG** [comment]
Hi Josh,

The timeline you mentioned lines up exactly with what we've seen on our side. The impacted period is between May 4th to 11th, after which we did see the issue go away.

What is the best way for us to get visibility into ongoing/open issues with Ads API/processing that may be affecting us?

Thanks for your help,
Austin

**Comment by jradcliff** [comment]
Hi Austin,

The first place to check is the status dashboard at https://ads.google.com/status/publisher/. In addition, depending on the type of issue, we may also publish to our developer's blog at https://ads-developers.googleblog.com/search/label/google_ads_api.

Finally, if you're encountering any unexpected behavior (regardless of the size of the issue), you can always reach out to us on our support forum at https://groups.google.com/forum/#!forum/adwords-api. That's the best choice if the issue you are seeing is not specific to the client library as well.

Thanks,
Josh, Google Ads API Team
