### ISSUE TITLE
Goggle Ads API v14-java.lang.NoSuchMethodError: com.google.api.client.util.escape.PercentEscaper.<init>(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by saurabhsumanbbsr** [googleads/google-ads-java#724]
While testing GetCampaigns operation using v14 ads api in java we are getting the below error .We are using pom dependency as below
com.google.api-ads
google-ads
26.0.0
**Error**:
2023-07-27 16:25:19,938 ERROR [main] A: C: AccountDownloadTask:78 - com.google.api.client.util.escape.PercentEscaper.(Ljava/lang/String;)V
java.lang.NoSuchMethodError: com.google.api.client.util.escape.PercentEscaper.(Ljava/lang/String;)V
at com.google.api.gax.rpc.RequestUrlParamsEncoder.(RequestUrlParamsEncoder.java:47)
at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.(GrpcUnaryRequestParamCallable.java:54)
at com.google.api.gax.grpc.GrpcRawCallableFactory.createUnaryCallable(GrpcRawCallableFactory.java:59)
at com.google.api.gax.grpc.GrpcCallableFactory.createBaseUnaryCallable(GrpcCallableFactory.java:85)
at com.google.ads.googleads.lib.GrpcGoogleAdsCallableFactory.createBaseUnaryCallable(GrpcGoogleAdsCallableFactory.java:70)
at com.google.ads.googleads.lib.GrpcGoogleAdsCallableFactory.createUnaryCallable(GrpcGoogleAdsCallableFactory.java:80)
at com.google.longrunning.stub.GrpcOperationsStub.(GrpcOperationsStub.java:226)
at com.google.longrunning.stub.GrpcOperationsStub.create(GrpcOperationsStub.java:133)
at com.google.ads.googleads.v14.services.stub.GrpcGoogleAdsServiceStub.(GrpcGoogleAdsServiceStub.java:132)
at com.google.ads.googleads.v14.services.stub.GrpcGoogleAdsServiceStub.(GrpcGoogleAdsServiceStub.java:118)
at com.google.ads.googleads.v14.services.stub.GrpcGoogleAdsServiceStub.create(GrpcGoogleAdsServiceStub.java:96)
at com.google.ads.googleads.v14.services.stub.GoogleAdsServiceStubSettings.createStub(GoogleAdsServiceStubSettings.java:189)
at com.google.ads.googleads.v14.services.GoogleAdsServiceClient.(GoogleAdsServiceClient.java:150)
at com.google.ads.googleads.v14.services.GoogleAdsServiceClient.create(GoogleAdsServiceClient.java:132)
at com.google.ads.googleads.lib.catalog.GeneratedCatalog$V14Client.createGoogleAdsServiceClient(GeneratedCatalog.java:4594)

**Comment by jradcliff** [comment]
Please inspect your dependencies as [described in our guide](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#shadow_dependencies). If you are unable to resolve the issue based on that, please share the output from the command listed there.

Thanks,
Josh, Google Ads API Team

**Comment by saurabhsumanbbsr** [comment]
Hi Josh, 
  After including the google-ads-shadowjar dependency  along with google-ads   in pom.xml  for v14 now the  code is working fine.

	<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads</artifactId>
		<version>26.0.0</version>
	</dependency>

	**<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads-shadowjar</artifactId>
		<version>26.0.0</version>
	</dependency>.**

After adding shadow dependency we got an error  like below which we resolved by including bollean parameter in method.

Error:(340, 17) java: method addQueryParams in class com.google.api.client.http.GenericUrl cannot be applied to given types;
  required: java.util.Set<java.util.Map.Entry<java.lang.String,java.lang.Object>>,java.lang.StringBuilder,boolean
  found: java.util.Set<java.util.Map.Entry<java.lang.String,java.lang.Object>>,java.lang.StringBuilder
  reason: actual and formal argument lists differ in length

**Comment by jradcliff** [comment]
Those errors suggest you have a dependency on an old version of `com.google.http-client:google-http-client`. The library expects `com.google.http-client:google-http-client:1.43.1`, but it looks like your pom may be pulling in a much older version, perhaps via another dependency.

**Comment by saurabhsumanbbsr** [comment]
For now with below dependencies simultaneously being included all errors have been resolved in local env. Please confirm  if we need to add google-ads-shadowjar-26.0.0 along with google-ads-26.0.0.jar  in prod nexus repository to get this  work in production environment.

<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads</artifactId>
		<version>26.0.0</version>
	</dependency>

	<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads-shadowjar</artifactId>
		<version>26.0.0</version>
	</dependency>

**Comment by jradcliff** [comment]
You should depend on *either* `google-ads` *or* `google-ads-shadowjar`, but not both. I would suggest using `google-ads` and determining which of the other dependencies in your `pom.xml` are conflicting with that and causing the errors. If you are unable to resolve those dependency issues, then you could use `google-ads-shadowjar` instead.

If you run the [commands in the guide](https://developers.google.com/google-ads/api/docs/client-libs/java/advanced-usage#shadow_dependencies) and share the output here, I can take a look and help you figure out which dependencies are conflicting.

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Yes, that sounds right to me.

**Comment by phonRathana** [comment]
Daer Thanks a lot for letting me know I'm trying to fix it, I'm going to
learn more about the API.🙏🙏🙏

នៅ​ថ្ងៃទី ព្រហ 3 សីហា 2023, 2:09 AM Josh Radcliff ***@***.***>
បាន​សរសេរ​ថា៖

**Comment by saurabhsumanbbsr** [comment]
As discussed , removed the shadow dependency and tested by upgrading below google-http-client(  from 1.26.0  to 1.43.1) dependency. Currently  we have only two changes in dependencies. Currently code is working fine. Please close the issue.

<dependency>
		<groupId>com.google.api-ads</groupId>
		<artifactId>google-ads</artifactId>
		<version>26.0.0</version>
	</dependency>
<dependency>
    	<groupId>com.google.http-client</groupId>
    	<artifactId>google-http-client</artifactId>
    	<version>1.43.1</version>
	</dependency>
