### ISSUE TITLE
CONVERSION_TRACKING_NOT_ENABLED error when attempting to create Campaign

### ISSUE THREAD

**Issue by madc0w** [googleads/google-ads-java#810]
We were recently required to upgrade from v16 to v17, and now creating conversion-driven Campaigns is failing. We can find no mention of changes to conversion-driven ads in the release notes.

What changed, and how can  we make this work again?

pom.xml entry:

```
		<dependency>
			<groupId>com.google.api-ads</groupId>
			<artifactId>google-ads</artifactId>
			<version>33.0.0</version>
		</dependency>

```
Code:

```
				final Campaign.Builder campaignBuilder = Campaign.newBuilder(). //
						setName(campaignName). //
						setTargetSpend(targetSpend). //
						setAdvertisingChannelType(AdvertisingChannelType.SEARCH). //
						// set to PAUSED when creating it to prevent ads from immediately serving
						setStatus(CampaignStatus.PAUSED). //
						setCampaignBudget(budgetResourceName). //
						setNetworkSettings(networkSettings). //
						setEndDate(paramDateFormat.format(endDate)) //
				;

				// this is the bit causes the failure:
				campaignBuilder.setBiddingStrategyType(BiddingStrategyType.MAXIMIZE_CONVERSIONS);
				campaignBuilder.setMaximizeConversions(MaximizeConversions.newBuilder().build());

				final Campaign campaign = campaignBuilder.build();

```

And here is the stack trace:

```
Sep 28 15:28:24  MethodName: google.ads.googleads.v17.services.CampaignService/MutateCampaigns
Sep 28 15:28:24  Endpoint: googleads.googleapis.com:443
Sep 28 15:28:24  Headers: {developer-token=REDACTED, login-customer-id=5839428813, x-goog-api-client=gl-java/1.8.0_422__Azul-Systems--Inc. gccl/33.0.0 gapic/33.0.0 gax/2.51.0 grpc/1.65.1}
Sep 28 15:28:24  Body: customer_id: "2419093460"
Sep 28 15:28:24  operations {
Sep 28 15:28:24    create {
Sep 28 15:28:24      status: PAUSED
Sep 28 15:28:24      advertising_channel_type: SEARCH
Sep 28 15:28:24      network_settings {
Sep 28 15:28:24        target_google_search: true
Sep 28 15:28:24        target_search_network: false
Sep 28 15:28:24        target_content_network: false
Sep 28 15:28:24        target_partner_search_network: false
Sep 28 15:28:24      }
Sep 28 15:28:24      bidding_strategy_type: MAXIMIZE_CONVERSIONS
Sep 28 15:28:24      maximize_conversions {
Sep 28 15:28:24      }
Sep 28 15:28:24      name: "ca id: 66f70151d22f3feac2ed09bc, uid: 66ca32310e9ecb79022a5930, iid: 66ccc552f637e7a99b521dfa, bid: 5 : Sat Sep 28 15:28:23 CEST 2024"
Sep 28 15:28:24      campaign_budget: "customers/2419093460/campaignBudgets/13954584437"
Sep 28 15:28:24      end_date: "20241028"
Sep 28 15:28:24    }
Sep 28 15:28:24  }
Sep 28 15:28:24 
Sep 28 15:28:24 
Sep 28 15:28:24  Response
Sep 28 15:28:24  --------
Sep 28 15:28:24  Headers: Metadata(content-type=application/grpc,request-id=Om3z2nocL4GcGshUlJzVsA,date=Sat, 28 Sep 2024 13:28:23 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000)
Sep 28 15:28:24  Body: null
Sep 28 15:28:24  Failure message: errors {
Sep 28 15:28:24    error_code {
Sep 28 15:28:24      campaign_error: CONVERSION_TRACKING_NOT_ENABLED
Sep 28 15:28:24    }
Sep 28 15:28:24    message: "Conversion tracking is not enabled and is required for this feature."
Sep 28 15:28:24    location {
Sep 28 15:28:24      field_path_elements {
Sep 28 15:28:24        field_name: "operations"
Sep 28 15:28:24        index: 0
Sep 28 15:28:24      }
Sep 28 15:28:24      field_path_elements {
Sep 28 15:28:24        field_name: "create"
Sep 28 15:28:24      }
Sep 28 15:28:24      field_path_elements {
Sep 28 15:28:24        field_name: "maximize_conversions"
Sep 28 15:28:24      }
Sep 28 15:28:24    }
Sep 28 15:28:24  }
Sep 28 15:28:24  request_id: "Om3z2nocL4GcGshUlJzVsA" 

Sep 28 15:28:24  Status: Status{code=INVALID_ARGUMENT, description=Request contains an invalid argument., cause=null}.
Sep 28 15:28:24  throwable type: com.google.ads.googleads.v17.errors.GoogleAdsException
Sep 28 15:28:24  com.google.ads.googleads.v17.errors.GoogleAdsException: errors {
Sep 28 15:28:24    error_code {
Sep 28 15:28:24      campaign_error: CONVERSION_TRACKING_NOT_ENABLED
Sep 28 15:28:24    }
Sep 28 15:28:24    message: "Conversion tracking is not enabled and is required for this feature."
Sep 28 15:28:24    location {
Sep 28 15:28:24      field_path_elements {
Sep 28 15:28:24        field_name: "operations"
Sep 28 15:28:24        index: 0
Sep 28 15:28:24      }
Sep 28 15:28:24      field_path_elements {
Sep 28 15:28:24        field_name: "create"
Sep 28 15:28:24      }
Sep 28 15:28:24      field_path_elements {
Sep 28 15:28:24        field_name: "maximize_conversions"
Sep 28 15:28:24      }
Sep 28 15:28:24    }
Sep 28 15:28:24  }
Sep 28 15:28:24  request_id: "Om3z2nocL4GcGshUlJzVsA"
Sep 28 15:28:24 
Sep 28 15:28:24  	at com.google.ads.googleads.v17.errors.GoogleAdsException$Factory.createException(GoogleAdsException.java:42)
Sep 28 15:28:24  	at com.google.ads.googleads.v17.errors.GoogleAdsException$Factory.createException(GoogleAdsException.java:34)
Sep 28 15:28:24  	at com.google.ads.googleads.lib.stubs.exceptions.BaseGoogleAdsException$Factory.createGoogleAdsException(BaseGoogleAdsException.java:105)
Sep 28 15:28:24  	at com.google.ads.googleads.lib.callables.GoogleAdsExceptionTransformation.transform(GoogleAdsExceptionTransformation.java:39)
Sep 28 15:28:24  	at com.google.ads.googleads.lib.stubs.callables.ExceptionTransformingUnaryCallable$ExceptionTransformingFuture.onFailure(ExceptionTransformingUnaryCallable.java:96)
Sep 28 15:28:24  	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
Sep 28 15:28:24  	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1130)
Sep 28 15:28:24  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Sep 28 15:28:24  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Sep 28 15:28:24  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Sep 28 15:28:24  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Sep 28 15:28:24  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Sep 28 15:28:24  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Sep 28 15:28:24  	at java.lang.Thread.run(Thread.java:750)
Sep 28 15:28:24  	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
Sep 28 15:28:24  		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
Sep 28 15:28:24  		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
Sep 28 15:28:24  		at com.google.ads.googleads.v17.services.CampaignServiceClient.mutateCampaigns(CampaignServiceClient.java:254)
Sep 28 15:28:24  		at com.google.ads.googleads.v17.services.CampaignServiceClient.mutateCampaigns(CampaignServiceClient.java:213)
Sep 28 15:28:24  		at app.LaunchGoogleCampaign.go(LaunchGoogleCampaign.java:279)
Sep 28 15:28:24  		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Sep 28 15:28:24  		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Sep 28 15:28:24  		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Sep 28 15:28:24  		at java.lang.reflect.Method.invoke(Method.java:498)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
Sep 28 15:28:24  		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
Sep 28 15:28:24  		at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
Sep 28 15:28:24  		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
Sep 28 15:28:24  		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
Sep 28 15:28:24  		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
Sep 28 15:28:24  		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
Sep 28 15:28:24  		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
Sep 28 15:28:24  		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
Sep 28 15:28:24  		at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
Sep 28 15:28:24  		at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
Sep 28 15:28:24  		at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:353)
Sep 28 15:28:24  		at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
Sep 28 15:28:24  		at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
Sep 28 15:28:24  		at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
Sep 28 15:28:24  		... 1 more
Sep 28 15:28:24  Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
Sep 28 15:28:24  	at io.grpc.Status.asRuntimeException(Status.java:533)
Sep 28 15:28:24  	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
Sep 28 15:28:24  	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Sep 28 15:28:24  	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Sep 28 15:28:24  	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Sep 28 15:28:24  	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:569)
Sep 28 15:28:24  	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Sep 28 15:28:24  	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Sep 28 15:28:24  	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Sep 28 15:28:24  	at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:113)
Sep 28 15:28:24  	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
Sep 28 15:28:24  	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
Sep 28 15:28:24  	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
Sep 28 15:28:24  	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:564)
Sep 28 15:28:24  	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:72)
Sep 28 15:28:24  	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:729)
Sep 28 15:28:24  	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:710)
Sep 28 15:28:24  	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
Sep 28 15:28:24  	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
Sep 28 15:28:24  	... 3 more
Sep 28 15:28:24  err.getErrorCode().getAuthenticationError() UNSPECIFIED
Sep 28 15:28:24  err.getErrorCode().getAuthorizationError() UNSPECIFIED 


```

**Comment by jradcliff** [comment]
Hi,

This isn't an issue with the library, but rather a product requirement. Google Ads requires that you set up conversion tracking in order to use the MAXIMIZE_CONVERSIONS bidding strategy. You can read about setting up conversion tracking at https://developers.google.com/google-ads/api/docs/conversions/getting-started#enable_conversion_tracking.

If you have further questions about this, please reach out to support:

https://developers.google.com/google-ads/api/support

Thanks,
Josh
